# Dockerfile: OPS360 Ethan-Home-Appliances
# Optimized for Google Cloud Run (Next.js Standalone Mode)

FROM node:20-alpine AS base
WORKDIR /app

# Step 1: Install Dependencies
FROM base AS deps
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json ./
RUN npm ci

# Step 2: Build the Application
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED 1

# ARG-based Public Environment Variables (Passed at build time)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY

# Provide dummy variables for Next.js standalone build to prevent crashes
ENV DATABASE_URL="postgres://dummy:dummy@localhost:5432/dummy"
ENV NEXTAUTH_SECRET="dummy_secret_for_build_only_1234567890"
ENV NEXTAUTH_URL="http://localhost:3000"

RUN npm run build

# Step 3: Production Runner (Final Thin Image)
FROM base AS runner
ENV NODE_ENV production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy essential runtime files from builder
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Note: server.js is generated by standalone mode
CMD ["node", "server.js"]
