const fs = require('fs');
let content = fs.readFileSync('src/actions/finance.ts', 'utf8');

const newFunc = \// -- getJournalEntries -------------------------------
export async function getJournalEntries(input?: { branchId?: string; fromDate?: string; toDate?: string; source?: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const entries = await db
      .select({
        id:              journal_entries.id,
        date:            journal_entries.date,
        description:     journal_entries.description,
        referenceSource: journal_entries.reference_source,
        referenceId:     journal_entries.reference_id,
        branchId:        journal_entries.branch_id,
        financialYear:   journal_entries.financial_year,
        status:          journal_entries.status,
        autoGenerated:   journal_entries.auto_generated,
        branchName:      branches.name,
        amount:          sql<number>\\\COALESCE(SUM(\\\), 0)\\\.mapWith(Number),
      })
      .from(journal_entries)
      .leftJoin(branches, eq(journal_entries.branch_id, branches.id))
      .leftJoin(journal_lines, eq(journal_lines.journal_entry_id, journal_entries.id))
      .where(input?.branchId ? eq(journal_entries.branch_id, input.branchId) : undefined)
      .groupBy(journal_entries.id, branches.name)
      .orderBy(desc(journal_entries.date))
      .limit(200)

    return { success: true as const, entries }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// -- getJournalLines ---------------------------------
export async function getJournalLines(journalEntryId: string) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const lines = await db
      .select({
        id:          journal_lines.id,
        accountId:   journal_lines.account_id,
        accountName: chart_of_accounts.name,
        accountCode: chart_of_accounts.code,
        debit:       journal_lines.debit,
        credit:      journal_lines.credit,
        description: journal_lines.description,
      })
      .from(journal_lines)
      .leftJoin(chart_of_accounts, eq(journal_lines.account_id, chart_of_accounts.id))
      .where(eq(journal_lines.journal_entry_id, journalEntryId))
      .orderBy(desc(journal_lines.debit))

    return { success: true as const, lines }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}\;

content = content.replace(/\\/\\/ -- getJournalEntries -------------------------------[\\s\\S]*?return \\{ success: false as const, error: \\(error as Error\\)\\.message \\}\\n  \\}\\n\\}/, newFunc);
fs.writeFileSync('src/actions/finance.ts', content);
