const fs = require('fs');
let content = fs.readFileSync('src/actions/finance.ts', 'utf8');

// 1. Refactor getJournalEntries query
const getJournalEntriesOld = `    const entries = await db
      .select({
        id:              journal_entries.id,
        date:            journal_entries.date,
        description:     journal_entries.description,
        referenceSource: journal_entries.reference_source,
        referenceId:     journal_entries.reference_id,
        branchId:        journal_entries.branch_id,
        financialYear:   journal_entries.financial_year,
        status:          journal_entries.status,
        autoGenerated:   journal_entries.auto_generated,
        branchName:      branches.name,
        amount:          sql<number>\`(SELECT SUM(debit) FROM journal_lines WHERE journal_entry_id = \${journal_entries.id})\`.mapWith(Number),
      })
      .from(journal_entries)
      .leftJoin(branches, eq(journal_entries.branch_id, branches.id))
      .where(input?.branchId ? eq(journal_entries.branch_id, input.branchId) : undefined)
      .orderBy(desc(journal_entries.date))
      .limit(200)`;

const getJournalEntriesNew = `    const entries = await db
      .select({
        id:              journal_entries.id,
        date:            journal_entries.date,
        description:     journal_entries.description,
        referenceSource: journal_entries.reference_source,
        referenceId:     journal_entries.reference_id,
        branchId:        journal_entries.branch_id,
        financialYear:   journal_entries.financial_year,
        status:          journal_entries.status,
        autoGenerated:   journal_entries.auto_generated,
        branchName:      branches.name,
        amount:          sql<number>\`COALESCE(SUM(\${journal_lines.debit}), 0)\`.mapWith(Number),
      })
      .from(journal_entries)
      .leftJoin(branches, eq(journal_entries.branch_id, branches.id))
      .leftJoin(journal_lines, eq(journal_entries.id, journal_lines.journal_entry_id))
      .where(input?.branchId ? eq(journal_entries.branch_id, input.branchId) : undefined)
      .groupBy(
        journal_entries.id,
        journal_entries.date,
        journal_entries.description,
        journal_entries.reference_source,
        journal_entries.reference_id,
        journal_entries.branch_id,
        journal_entries.financial_year,
        journal_entries.status,
        journal_entries.auto_generated,
        branches.name
      )
      .orderBy(desc(journal_entries.date))
      .limit(200)`;

content = content.replace(getJournalEntriesOld, getJournalEntriesNew);

// 2. Add tx support to finance functions
content = content.replace('async function getAccountId(code: string): Promise<string> {', 'async function getAccountId(code: string, txClient: any = db): Promise<string> {');
content = content.replace('  const [account] = await db\\n    .select', '  const [account] = await txClient\\n    .select');

content = content.replace('export async function createJournalEntry(input: {\\n  date?: Date', 'export async function createJournalEntry(input: {\\n  date?: Date\\n  tx?: any');
content = content.replace('const financialYear = await getFinancialYear(date)\\n\\n  const [entry] = await db', 'const financialYear = await getFinancialYear(date)\\n  const dbClient = input.tx ?? db\\n\\n  const [entry] = await dbClient');
content = content.replace('account_id: await getAccountId(line.accountCode)', 'account_id: await getAccountId(line.accountCode, dbClient)');
content = content.replace('await db.insert(journal_lines).values(lineValues)', 'await dbClient.insert(journal_lines).values(lineValues)');

content = content.replace('export async function postGRNJournal(input: {\\n  grnId: string', 'export async function postGRNJournal(input: {\\n  tx?: any\\n  grnId: string');
content = content.replace('const totalPayable = input.totalLandedCost + totalGST\\n\\n  const [grn] = await db', 'const totalPayable = input.totalLandedCost + totalGST\\n  const dbClient = input.tx ?? db\\n\\n  const [grn] = await dbClient');
content = content.replace('  const [po] = await db', '  const [po] = await dbClient');
content = content.replace('createdBy: input.createdBy,\\n    lines,\\n  })\\n}', 'createdBy: input.createdBy,\\n    lines,\\n    tx: dbClient,\\n  })\\n}');

content = content.replace('export async function postSalesJournal(input: {\\n  invoiceId: string', 'export async function postSalesJournal(input: {\\n  tx?: any\\n  invoiceId: string');
content = content.replace('createdBy: input.createdBy,\\n    lines,\\n  })\\n}', 'createdBy: input.createdBy,\\n    lines,\\n    tx: input.tx ?? db,\\n  })\\n}');

fs.writeFileSync('src/actions/finance.ts', content);
console.log('finance.ts patched successfully');
