"use client"

import React from 'react'

// ── Types ───────────────────────────────────────────

type PLRow  = { code: string; name: string; net: string }
type BSRow  = { code: string; name: string; balance: string }
type GSTRow = { code: string; name: string; collected: string; paid: string }

interface FinancePrintTemplateProps {
  reportType: 'pl' | 'balance-sheet' | 'gst' | 'journal' | 'expenses'
  fromDate: string
  toDate: string
  financialYear?: string
  branchName?: string

  // P&L data
  plRevenue?: PLRow[]
  plExpenses?: PLRow[]
  totalRevenue?: number
  totalExpenses?: number
  netProfit?: number

  // Balance Sheet data
  bsAssets?: BSRow[]
  bsLiabilities?: BSRow[]
  bsEquity?: BSRow[]

  // GST data
  gstRows?: GSTRow[]

  // Journal data
  journalEntries?: Array<{
    date: Date | string
    description: string
    referenceSource: string
    branchName: string | null
    financialYear: string
    autoGenerated: boolean
    status: string
  }>

  // Expense data
  expenses?: Array<{
    created_at: Date | string
    description: string
    expense_account: string
    payment_account: string
    amount: string
    status: string
  }>
}

// ── Helpers ─────────────────────────────────────────

function fmtINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
  }).format(amount)
}

function fmtDate(date: Date | string): string {
  return new Date(date).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
  })
}

const EXPENSE_ACCOUNTS: Record<string, string> = {
  '5010': 'Cost of Goods Sold',
  '5020': 'Freight & Logistics',
  '5030': 'Utilities',
  '5040': 'Rent',
  '5050': 'Salaries & Wages',
  '5060': 'Marketing & Advertising',
  '5070': 'Miscellaneous Expense',
}

const PAYMENT_ACCOUNTS: Record<string, string> = {
  '1010': 'Cash & Petty Cash',
  '1020': 'Bank Accounts',
}

// ── Component ────────────────────────────────────────

export const FinancePrintTemplate =
  React.forwardRef<HTMLDivElement, FinancePrintTemplateProps>(
    (props, ref) => {
      const {
        reportType, fromDate, toDate, branchName,
        plRevenue = [], plExpenses = [],
        totalRevenue = 0, totalExpenses = 0, netProfit = 0,
        bsAssets = [], bsLiabilities = [], bsEquity = [],
        gstRows = [],
        journalEntries = [],
        expenses = [],
      } = props

      const systemTimestamp = new Date().toLocaleString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit', second: '2-digit',
      })

      const reportTitles: Record<string, string> = {
        'pl':            'Profit & Loss Statement',
        'balance-sheet': 'Balance Sheet',
        'gst':           'GST Summary Report',
        'journal':       'Journal Ledger',
        'expenses':      'Expense Report',
      }

      const reportTitle = reportTitles[reportType]

      return (
        <div
          ref={ref}
          id="finance-print-template"
          className="bg-white text-slate-900 w-[210mm] min-h-[297mm] mx-auto font-sans relative [print-color-adjust:exact] [-webkit-print-color-adjust:exact]"
        >
          {/* ── Print styles ── */}
          <style dangerouslySetInnerHTML={{ __html: `
            @media print {
              @page {
                size: A4 portrait;
                margin: 10mm;
              }
              body {
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
                background: white !important;
              }
              #finance-print-template {
                width: 100% !important;
                height: auto !important;
                overflow: visible !important;
                padding: 0 !important;
                margin: 0 !important;
              }
            }
          `}} />

          {/* ── Header — matches PO/GRN style ── */}
          <div style={{ backgroundColor: '#001529' }}
            className="text-white px-10 py-5 flex justify-between items-center">
            <div>
              <h1 className="text-2xl font-bold tracking-tight m-0 leading-tight">
                {reportTitle}
              </h1>
              <p className="text-sm mt-1 m-0" style={{ color: '#94a3b8' }}>
                Period: {fmtDate(fromDate)} — {fmtDate(toDate)}
              </p>
              {branchName && (
                <p className="text-xs mt-0.5 m-0" style={{ color: '#64748b' }}>
                  Branch: {branchName}
                </p>
              )}
            </div>
            <div className="flex items-center gap-4">
              <div className="text-right">
                <p className="font-semibold text-sm m-0 uppercase tracking-tight">
                  Ethan Home Appliances
                </p>
                <p className="text-xs m-0" style={{ color: '#94a3b8' }}>
                  OPS360 Enterprise ERP
                </p>
              </div>
              <div className="bg-white rounded p-1">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src="/ethan-logo.png"
                  width={36}
                  height={36}
                  alt="Ethan Logo"
                  style={{ height: '32px', width: 'auto', objectFit: 'contain' }}
                />
              </div>
            </div>
          </div>

          {/* ── Company address block ── */}
          <div className="px-10 py-4 border-b flex justify-between items-start"
            style={{ backgroundColor: '#f8fafc', fontSize: '10px', color: '#475569' }}>
            <div>
              <p className="font-black uppercase tracking-widest m-0 mb-1"
                style={{ color: '#0f172a', fontSize: '9px' }}>
                Issued By
              </p>
              <p className="font-bold m-0" style={{ color: '#0f172a' }}>
                Ethan Home Appliances HQ
              </p>
              <p className="m-0">Minzta Hotel, Vazhappilly Tower, Koratty</p>
              <p className="m-0">Thrissur, Kerala</p>
              <p className="m-0">Contact: 9747552277 | ethanops360@gmail.com</p>
            </div>
            <div className="text-right">
              <p className="font-black uppercase tracking-widest m-0 mb-1"
                style={{ color: '#0f172a', fontSize: '9px' }}>
                Document Info
              </p>
              <p className="m-0" suppressHydrationWarning>
                Generated: {systemTimestamp}
              </p>
              <p className="m-0">Report Type: {reportTitle}</p>
              <p className="m-0 mt-1" style={{ color: '#94a3b8', fontSize: '9px' }}>
                ELECTRONICALLY GENERATED — NO SIGNATURE REQUIRED
              </p>
            </div>
          </div>

          {/* ── Report content ── */}
          <div className="px-10 py-6">

            {/* ── P&L Report ── */}
            {reportType === 'pl' && (
              <div className="space-y-6">

                {/* Summary row */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '16px' }}>
                  {[
                    { label: 'Total Revenue',   value: totalRevenue,  color: '#15803d' },
                    { label: 'Total Expenses',  value: totalExpenses, color: '#b91c1c' },
                    { label: 'Net Profit / Loss', value: netProfit,
                      color: netProfit >= 0 ? '#4338ca' : '#c2410c' },
                  ].map(card => (
                    <div key={card.label}
                      style={{ border: '1px solid #e2e8f0', borderRadius: '8px',
                        padding: '16px', textAlign: 'center' }}>
                      <p style={{ fontSize: '9px', color: '#64748b', textTransform: 'uppercase',
                        letterSpacing: '0.1em', margin: '0 0 4px 0' }}>
                        {card.label}
                      </p>
                      <p style={{ fontSize: '20px', fontWeight: 700,
                        color: card.color, margin: 0 }}>
                        {fmtINR(card.value)}
                      </p>
                    </div>
                  ))}
                </div>

                {/* Revenue table */}
                <div>
                  <h2 style={{ fontSize: '11px', fontWeight: 700, color: '#15803d',
                    textTransform: 'uppercase', letterSpacing: '0.1em',
                    margin: '0 0 8px 0' }}>
                    Revenue
                  </h2>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f1f5f9' }}>
                        <th style={{ textAlign: 'left', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Code</th>
                        <th style={{ textAlign: 'left', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Account</th>
                        <th style={{ textAlign: 'right', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                      {plRevenue.map(r => (
                        <tr key={r.code} style={{ borderBottom: '1px solid #f1f5f9' }}>
                          <td style={{ padding: '8px 12px', color: '#64748b', fontSize: '10px' }}>{r.code}</td>
                          <td style={{ padding: '8px 12px' }}>{r.name}</td>
                          <td style={{ padding: '8px 12px', textAlign: 'right', color: '#15803d', fontWeight: 500 }}>
                            {fmtINR(Number(r.net))}
                          </td>
                        </tr>
                      ))}
                      <tr style={{ backgroundColor: '#f0fdf4', fontWeight: 700,
                        borderTop: '2px solid #bbf7d0' }}>
                        <td colSpan={2} style={{ padding: '8px 12px' }}>Total Revenue</td>
                        <td style={{ padding: '8px 12px', textAlign: 'right', color: '#15803d' }}>
                          {fmtINR(totalRevenue)}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>

                {/* Expenses table */}
                <div>
                  <h2 style={{ fontSize: '11px', fontWeight: 700, color: '#b91c1c',
                    textTransform: 'uppercase', letterSpacing: '0.1em',
                    margin: '0 0 8px 0' }}>
                    Expenses
                  </h2>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f1f5f9' }}>
                        <th style={{ textAlign: 'left', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Code</th>
                        <th style={{ textAlign: 'left', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Account</th>
                        <th style={{ textAlign: 'right', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                      {plExpenses.map(e => (
                        <tr key={e.code} style={{ borderBottom: '1px solid #f1f5f9' }}>
                          <td style={{ padding: '8px 12px', color: '#64748b', fontSize: '10px' }}>{e.code}</td>
                          <td style={{ padding: '8px 12px' }}>{e.name}</td>
                          <td style={{ padding: '8px 12px', textAlign: 'right', color: '#b91c1c', fontWeight: 500 }}>
                            {fmtINR(Math.abs(Number(e.net)))}
                          </td>
                        </tr>
                      ))}
                      <tr style={{ backgroundColor: '#fff1f2', fontWeight: 700,
                        borderTop: '2px solid #fecdd3' }}>
                        <td colSpan={2} style={{ padding: '8px 12px' }}>Total Expenses</td>
                        <td style={{ padding: '8px 12px', textAlign: 'right', color: '#b91c1c' }}>
                          {fmtINR(totalExpenses)}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>

                {/* Net profit footer */}
                <div style={{
                  border: `2px solid ${netProfit >= 0 ? '#c7d2fe' : '#fed7aa'}`,
                  borderRadius: '12px', padding: '16px', textAlign: 'center',
                  backgroundColor: netProfit >= 0 ? '#eef2ff' : '#fff7ed',
                }}>
                  <p style={{ fontSize: '9px', textTransform: 'uppercase',
                    letterSpacing: '0.1em', color: '#64748b', margin: '0 0 4px 0' }}>
                    Net Profit / Loss
                  </p>
                  <p style={{ fontSize: '28px', fontWeight: 700, margin: 0,
                    color: netProfit >= 0 ? '#4338ca' : '#c2410c' }}>
                    {fmtINR(netProfit)}
                  </p>
                  <p style={{ fontSize: '10px', color: '#64748b', margin: '4px 0 0 0' }}>
                    {netProfit >= 0 ? '▲ Profitable period' : '▼ Net loss for period'}
                  </p>
                </div>
              </div>
            )}

            {/* ── Balance Sheet ── */}
            {reportType === 'balance-sheet' && (
              <div className="space-y-6">
                {([
                  { title: 'Assets',      rows: bsAssets,      color: '#1d4ed8', bg: '#eff6ff', border: '#bfdbfe' },
                  { title: 'Liabilities', rows: bsLiabilities, color: '#b91c1c', bg: '#fff1f2', border: '#fecdd3' },
                  { title: 'Equity',      rows: bsEquity,      color: '#15803d', bg: '#f0fdf4', border: '#bbf7d0' },
                ] as const).map(section => (
                  <div key={section.title}>
                    <h2 style={{ fontSize: '11px', fontWeight: 700, color: section.color,
                      textTransform: 'uppercase', letterSpacing: '0.1em', margin: '0 0 8px 0' }}>
                      {section.title}
                    </h2>
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
                      <thead>
                        <tr style={{ backgroundColor: '#f1f5f9' }}>
                          <th style={{ textAlign: 'left', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Code</th>
                          <th style={{ textAlign: 'left', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Account</th>
                          <th style={{ textAlign: 'right', padding: '8px 12px', fontSize: '10px', fontWeight: 700 }}>Balance</th>
                        </tr>
                      </thead>
                      <tbody>
                        {section.rows.map(r => (
                          <tr key={r.code} style={{ borderBottom: '1px solid #f1f5f9' }}>
                            <td style={{ padding: '8px 12px', color: '#64748b', fontSize: '10px' }}>{r.code}</td>
                            <td style={{ padding: '8px 12px' }}>{r.name}</td>
                            <td style={{ padding: '8px 12px', textAlign: 'right', color: section.color, fontWeight: 500 }}>
                              {fmtINR(Number(r.balance))}
                            </td>
                          </tr>
                        ))}
                        <tr style={{ backgroundColor: section.bg, fontWeight: 700, borderTop: `2px solid ${section.border}` }}>
                          <td colSpan={2} style={{ padding: '8px 12px' }}>Total {section.title}</td>
                          <td style={{ padding: '8px 12px', textAlign: 'right', color: section.color }}>
                            {fmtINR(section.rows.reduce((s, r) => s + Number(r.balance), 0))}
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                ))}

                {/* Accounting equation */}
                <div style={{ border: '2px solid #e2e8f0', borderRadius: '12px',
                  padding: '16px', backgroundColor: '#f8fafc' }}>
                  <p style={{ fontSize: '9px', textTransform: 'uppercase',
                    letterSpacing: '0.1em', color: '#64748b', textAlign: 'center',
                    margin: '0 0 12px 0' }}>
                    Accounting Equation
                  </p>
                  <div style={{ display: 'flex', alignItems: 'center',
                    justifyContent: 'center', gap: '16px', textAlign: 'center' }}>
                    {[
                      { label: 'Assets',      value: bsAssets.reduce((s, r) => s + Number(r.balance), 0),      color: '#1d4ed8' },
                      { sep: '=' },
                      { label: 'Liabilities', value: bsLiabilities.reduce((s, r) => s + Number(r.balance), 0), color: '#b91c1c' },
                      { sep: '+' },
                      { label: 'Equity',      value: bsEquity.reduce((s, r) => s + Number(r.balance), 0),      color: '#15803d' },
                    ].map((item, i) =>
                      'sep' in item ? (
                        <span key={i} style={{ fontSize: '20px', color: '#94a3b8', fontWeight: 300 }}>
                          {item.sep}
                        </span>
                      ) : (
                        <div key={i}>
                          <p style={{ fontSize: '10px', color: '#64748b', margin: '0 0 2px 0' }}>{item.label}</p>
                          <p style={{ fontSize: '16px', fontWeight: 700, color: item.color, margin: 0 }}>
                            {fmtINR(item.value!)}
                          </p>
                        </div>
                      )
                    )}
                  </div>
                </div>
              </div>
            )}

            {/* ── GST Summary ── */}
            {reportType === 'gst' && (
              <div className="space-y-4">
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
                  <thead>
                    <tr style={{ backgroundColor: '#1e293b', color: '#fff' }}>
                      <th style={{ textAlign: 'left', padding: '10px 14px', fontSize: '10px', fontWeight: 700 }}>Code</th>
                      <th style={{ textAlign: 'left', padding: '10px 14px', fontSize: '10px', fontWeight: 700 }}>GST Account</th>
                      <th style={{ textAlign: 'right', padding: '10px 14px', fontSize: '10px', fontWeight: 700 }}>Output Tax (Collected)</th>
                      <th style={{ textAlign: 'right', padding: '10px 14px', fontSize: '10px', fontWeight: 700 }}>Input Tax / ITC</th>
                      <th style={{ textAlign: 'right', padding: '10px 14px', fontSize: '10px', fontWeight: 700 }}>Net Payable</th>
                    </tr>
                  </thead>
                  <tbody>
                    {gstRows.map(g => {
                      const net = Number(g.collected) - Number(g.paid)
                      return (
                        <tr key={g.code} style={{ borderBottom: '1px solid #f1f5f9' }}>
                          <td style={{ padding: '10px 14px', color: '#64748b', fontSize: '10px' }}>{g.code}</td>
                          <td style={{ padding: '10px 14px' }}>{g.name}</td>
                          <td style={{ padding: '10px 14px', textAlign: 'right', color: '#15803d', fontWeight: 500 }}>
                            {fmtINR(Number(g.collected))}
                          </td>
                          <td style={{ padding: '10px 14px', textAlign: 'right', color: '#1d4ed8', fontWeight: 500 }}>
                            {fmtINR(Number(g.paid))}
                          </td>
                          <td style={{ padding: '10px 14px', textAlign: 'right', fontWeight: 700,
                            color: net > 0 ? '#b91c1c' : '#15803d' }}>
                            {fmtINR(net)}
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                  <tfoot>
                    <tr style={{ backgroundColor: '#f1f5f9', fontWeight: 700, borderTop: '2px solid #cbd5e1' }}>
                      <td colSpan={2} style={{ padding: '10px 14px' }}>Total</td>
                      <td style={{ padding: '10px 14px', textAlign: 'right', color: '#15803d' }}>
                        {fmtINR(gstRows.reduce((s, g) => s + Number(g.collected), 0))}
                      </td>
                      <td style={{ padding: '10px 14px', textAlign: 'right', color: '#1d4ed8' }}>
                        {fmtINR(gstRows.reduce((s, g) => s + Number(g.paid), 0))}
                      </td>
                      <td style={{ padding: '10px 14px', textAlign: 'right', color: '#b91c1c' }}>
                        {fmtINR(gstRows.reduce((s, g) => s + Number(g.collected) - Number(g.paid), 0))}
                      </td>
                    </tr>
                  </tfoot>
                </table>

                <div style={{ padding: '12px 16px', backgroundColor: '#fffbeb',
                  border: '1px solid #fde68a', borderRadius: '8px',
                  fontSize: '10px', color: '#92400e' }}>
                  <p style={{ fontWeight: 700, margin: '0 0 4px 0' }}>GSTR Filing Note</p>
                  <p style={{ margin: 0 }}>
                    This report is generated from OPS360 ERP transaction data.
                    Verify all figures with your CA before filing GSTR-1, GSTR-3B, or annual returns.
                  </p>
                </div>
              </div>
            )}

            {/* ── Journal Ledger ── */}
            {reportType === 'journal' && (
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
                <thead>
                  <tr style={{ backgroundColor: '#1e293b', color: '#fff' }}>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Date</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Description</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Source</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Branch</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>FY</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Type</th>
                  </tr>
                </thead>
                <tbody>
                  {journalEntries.map((e, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                      <td style={{ padding: '8px 10px', color: '#64748b', fontSize: '10px', whiteSpace: 'nowrap' }}>
                        {fmtDate(e.date)}
                      </td>
                      <td style={{ padding: '8px 10px', maxWidth: '200px' }}>{e.description}</td>
                      <td style={{ padding: '8px 10px', fontSize: '10px' }}>{e.referenceSource}</td>
                      <td style={{ padding: '8px 10px', fontSize: '10px', color: '#64748b' }}>
                        {e.branchName ?? '—'}
                      </td>
                      <td style={{ padding: '8px 10px', fontSize: '10px', color: '#64748b' }}>
                        {e.financialYear}
                      </td>
                      <td style={{ padding: '8px 10px', fontSize: '10px' }}>
                        {e.autoGenerated ? 'Auto' : 'Manual'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}

            {/* ── Expense Report ── */}
            {reportType === 'expenses' && (
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
                <thead>
                  <tr style={{ backgroundColor: '#1e293b', color: '#fff' }}>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Date</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Description</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Category</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Payment</th>
                    <th style={{ textAlign: 'right', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Amount</th>
                    <th style={{ textAlign: 'left', padding: '8px 10px', fontSize: '10px', fontWeight: 700 }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {expenses.map((e, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                      <td style={{ padding: '8px 10px', color: '#64748b', fontSize: '10px', whiteSpace: 'nowrap' }}>
                        {fmtDate(e.created_at)}
                      </td>
                      <td style={{ padding: '8px 10px' }}>{e.description}</td>
                      <td style={{ padding: '8px 10px', fontSize: '10px' }}>
                        {EXPENSE_ACCOUNTS[e.expense_account] ?? e.expense_account}
                      </td>
                      <td style={{ padding: '8px 10px', fontSize: '10px', color: '#64748b' }}>
                        {PAYMENT_ACCOUNTS[e.payment_account] ?? e.payment_account}
                      </td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', fontWeight: 500 }}>
                        {fmtINR(Number(e.amount))}
                      </td>
                      <td style={{ padding: '8px 10px', fontSize: '10px', textTransform: 'capitalize' }}>
                        {e.status}
                      </td>
                    </tr>
                  ))}
                  <tr style={{ backgroundColor: '#f1f5f9', fontWeight: 700, borderTop: '2px solid #cbd5e1' }}>
                    <td colSpan={4} style={{ padding: '8px 10px' }}>Total</td>
                    <td style={{ padding: '8px 10px', textAlign: 'right' }}>
                      {fmtINR(expenses.reduce((s, e) => s + Number(e.amount), 0))}
                    </td>
                    <td />
                  </tr>
                </tbody>
              </table>
            )}

          </div>

          {/* ── Footer — matches PO/GRN style ── */}
          <div style={{ marginTop: '32px', borderTop: '1px solid #e2e8f0',
            backgroundColor: '#f8fafc', padding: '16px 40px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between',
              alignItems: 'center', fontSize: '9px', color: '#94a3b8',
              textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              <p style={{ margin: 0 }}>DOCUMENT VERIFICATION: OPS360 ENTERPRISE ERP</p>
              <p style={{ margin: 0 }} suppressHydrationWarning>
                RECEIPT TIMESTAMP: {systemTimestamp}
              </p>
              <p style={{ margin: 0 }}>© ELECTRONICALLY AUTHENTICATED</p>
            </div>
          </div>

        </div>
      )
    }
  )

FinancePrintTemplate.displayName = 'FinancePrintTemplate'
