'use server'

import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { db } from '@/db/client'
import {
  accounts, journal_entries, journal_lines,
  expense_records, branches, inventory,
  vendor_payments, purchase_orders, vendors, grn_receipts
} from '@/db/schema'
import { eq, desc, sql } from 'drizzle-orm'
import { getEffectiveBranchId } from '@/app/actions/_utils/branch'

// ── Helper: derive Indian financial year ────────────
export async function getFinancialYear(date: Date): Promise<string> {
  const month = date.getMonth() + 1
  const year = date.getFullYear()
  if (month >= 4) return `${year}-${String(year + 1).slice(2)}`
  return `${year - 1}-${String(year).slice(2)}`
}

// ── Helper: resolve account code → id ───────────────
async function getAccountId(code: string): Promise<string> {
  const [account] = await db
    .select({ id: accounts.id })
    .from(accounts)
    .where(eq(accounts.code, code))
    .limit(1)
  if (!account) throw new Error(`Account ${code} not found`)
  return account.id
}

// ── createJournalEntry ──────────────────────────────
export async function createJournalEntry(input: {
  date?: Date
  description: string
  referenceSource: string
  referenceId?: string
  branchId: string
  autoGenerated?: boolean
  createdBy: string
  lines: Array<{
    accountCode: string
    debit?: number
    credit?: number
    description?: string
  }>
}) {
  const totalDebit  = input.lines.reduce((s, l) => s + (l.debit  ?? 0), 0)
  const totalCredit = input.lines.reduce((s, l) => s + (l.credit ?? 0), 0)
  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new Error(
      `Journal entry is unbalanced: debits ${totalDebit} ≠ credits ${totalCredit}`
    )
  }

  const date = input.date ?? new Date()
  const financialYear = await getFinancialYear(date)

  const [entry] = await db
    .insert(journal_entries)
    .values({
      date,
      description: input.description,
      reference_source: input.referenceSource,
      reference_id: input.referenceId ?? null,
      branch_id: input.branchId,
      financial_year: financialYear,
      status: 'posted',
      auto_generated: input.autoGenerated ?? false,
      created_by: input.createdBy,
    })
    .returning()

  const lineValues = await Promise.all(
    input.lines.map(async (line) => ({
      journal_entry_id: entry.id,
      account_id: await getAccountId(line.accountCode),
      debit:  String(line.debit  ?? 0),
      credit: String(line.credit ?? 0),
      description: line.description ?? null,
    }))
  )

  await db.insert(journal_lines).values(lineValues)
  return entry
}

// ── postGRNJournal ──────────────────────────────────
// DR 1040 Inventory Asset, DR 1050 GST ITC, CR 2010 Payable
export async function postGRNJournal(input: {
  grnId: string
  poId: string
  branchId: string
  createdBy: string
  totalLandedCost: number
  totalGST: number
}) {
  const totalPayable = input.totalLandedCost + input.totalGST

  const [grn] = await db
    .select({ grnNumber: grn_receipts.grn_number })
    .from(grn_receipts)
    .where(eq(grn_receipts.id, input.grnId))
    .limit(1)

  const [po] = await db
    .select({ poNumber: purchase_orders.po_number })
    .from(purchase_orders)
    .where(eq(purchase_orders.id, input.poId))
    .limit(1)

  const grnRef = grn?.grnNumber ?? input.grnId
  const poRef = po?.poNumber ?? input.poId

  await createJournalEntry({
    description: `GRN: ${grnRef} (against ${poRef})`,
    referenceSource: 'GRN',
    referenceId: input.grnId,
    branchId: input.branchId,
    autoGenerated: true,
    createdBy: input.createdBy,
    lines: [
      { accountCode: '1040', debit: input.totalLandedCost, description: 'Inventory received — landed cost' },
      { accountCode: '1050', debit: input.totalGST,        description: 'GST Input Tax Credit on purchase' },
      { accountCode: '2010', credit: totalPayable,         description: 'Accounts payable to vendor' },
    ],
  })
}

// ── postSalesJournal ────────────────────────────────
// DR 1010 Cash, CR 4000 Revenue, CR GST Payable, DR 5010 COGS, CR 1040 Inventory
export async function postSalesJournal(input: {
  invoiceId: string
  branchId: string
  createdBy: string
  saleTotal: number
  subtotal: number
  cgst: number
  sgst: number
  igst: number
  cogs: number
}) {
  // If cogs not provided, calculate from inventory
  let cogsAmount = input.cogs

  if (cogsAmount === 0 && input.invoiceId) {
    try {
      const soldUnits = await db
        .select({ landedCost: inventory.landed_cost })
        .from(inventory)
        .where(eq(inventory.invoice_id, input.invoiceId))

      cogsAmount = soldUnits.reduce(
        (sum, unit) => sum + Number(unit.landedCost ?? 0),
        0
      )
    } catch {
      // If lookup fails, COGS stays 0 — don't block journal
      cogsAmount = 0
    }
  }

  const lines: Array<{ accountCode: string; debit?: number; credit?: number; description?: string }> = [
    { accountCode: '1010', debit: input.saleTotal, description: 'Cash received from POS sale' },
    { accountCode: '4000', credit: input.subtotal, description: 'Sales revenue ex-tax' },
  ]

  if (input.cgst > 0) lines.push({ accountCode: '2020', credit: input.cgst, description: 'CGST collected' })
  if (input.sgst > 0) lines.push({ accountCode: '2030', credit: input.sgst, description: 'SGST collected' })
  if (input.igst > 0) lines.push({ accountCode: '2040', credit: input.igst, description: 'IGST collected' })

  if (cogsAmount > 0) {
    lines.push(
      { accountCode: '5010', debit: cogsAmount,  description: 'Cost of goods sold' },
      { accountCode: '1040', credit: cogsAmount, description: 'Inventory asset reduced' }
    )
  }

  await createJournalEntry({
    description: 'Auto: POS sale invoice',
    referenceSource: 'SALES',
    referenceId: input.invoiceId,
    branchId: input.branchId,
    autoGenerated: true,
    createdBy: input.createdBy,
    lines,
  })
}

// ── createExpenseRecord ─────────────────────────────
export async function createExpenseRecord(input: {
  amount: number
  expenseAccount: string
  paymentAccount?: string
  description: string
  receiptUrl?: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const branchId = await getEffectiveBranchId(session)
  if (!branchId) return { success: false as const, error: 'No branch selected' }

  if (input.amount <= 0) return { success: false as const, error: 'Amount must be greater than 0' }

  try {
    await getAccountId(input.expenseAccount)
    await getAccountId(input.paymentAccount ?? '1010')
  } catch (e) {
    return { success: false as const, error: (e as Error).message }
  }

  const [record] = await db
    .insert(expense_records)
    .values({
      branch_id:       branchId,
      created_by:      session.user.id,
      amount:          String(input.amount),
      expense_account: input.expenseAccount,
      payment_account: input.paymentAccount ?? '1010',
      description:     input.description,
      receipt_url:     input.receiptUrl ?? null,
      status:          'pending',
    })
    .returning()

  return { success: true as const, record }
}

// ── approveExpense ──────────────────────────────────
export async function approveExpense(input: { expenseId: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const role = (session.user.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'admin/owner', 'manager'].includes(role)) {
    return { success: false as const, error: 'Manager role required' }
  }

  const [expense] = await db
    .select()
    .from(expense_records)
    .where(eq(expense_records.id, input.expenseId))
    .limit(1)

  if (!expense) return { success: false as const, error: 'Expense not found' }
  if (expense.status !== 'pending') {
    return { success: false as const, error: `Cannot approve expense with status: ${expense.status}` }
  }

  const entry = await createJournalEntry({
    description: `Expense: ${expense.description}`,
    referenceSource: 'EXPENSE',
    referenceId: expense.id,
    branchId: expense.branch_id,
    autoGenerated: false,
    createdBy: session.user.id,
    lines: [
      { accountCode: expense.expense_account, debit: Number(expense.amount), description: expense.description },
      { accountCode: expense.payment_account, credit: Number(expense.amount), description: 'Payment from cash/bank' },
    ],
  })

  await db
    .update(expense_records)
    .set({ status: 'approved', approved_by: session.user.id, approved_at: new Date(), journal_entry_id: entry.id })
    .where(eq(expense_records.id, input.expenseId))

  return { success: true as const, entry }
}

export async function settleVendorPayment(input: {
  poId: string
  amount: number
  paymentMethod: string  // bank|cash|upi|cheque
  referenceNumber?: string
  notes?: string
  paymentDate?: Date
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return { success: false as const, error: 'Unauthorized' }
  }

  const role = (session.user.role ?? '').toLowerCase()
  const isManager = ['admin', 'super_admin', 'admin/owner',
    'manager'].includes(role)
  if (!isManager) {
    return {
      success: false as const,
      error: 'Manager role required to record payments'
    }
  }

  if (input.amount <= 0) {
    return {
      success: false as const,
      error: 'Payment amount must be greater than 0'
    }
  }

  // Get PO with vendor info
  const [po] = await db
    .select({
      id: purchase_orders.id,
      po_number: purchase_orders.po_number,
      vendor_id: purchase_orders.vendor_id,
      branch_id: purchase_orders.branch_id,
      total_amount: purchase_orders.total_amount,
      status: purchase_orders.status,
    })
    .from(purchase_orders)
    .where(eq(purchase_orders.id, input.poId))
    .limit(1)

  if (!po) {
    return { success: false as const, error: 'PO not found' }
  }

  // Calculate total paid so far
  const existingPayments = await db
    .select({ amount: vendor_payments.amount })
    .from(vendor_payments)
    .where(eq(vendor_payments.po_id, input.poId))
    
  const totalPaid = existingPayments.reduce((sum, p) => sum + Number(p.amount ?? 0), 0)
  const poTotal = Number(po.total_amount ?? 0)
  const remainingBalance = Number((poTotal - totalPaid).toFixed(2))

  if (input.amount > remainingBalance + 0.01) { // 1 paisa tolerance
    return {
      success: false as const,
      error: `Payment amount (₹${input.amount}) exceeds remaining balance (₹${remainingBalance})`
    }
  }

  // Only settled/received POs can be paid
  const payableStatuses = [
    'received', 'partially_received',
    'approved', 'PARTIALLY_RETURNED', 'RETURNED'
  ]
  if (!payableStatuses.includes(po.status ?? '')) {
    return {
      success: false as const,
      error: `Cannot record payment for PO with status: ${po.status}`
    }
  }

  // Determine payment account from method
  const paymentAccountCode =
    input.paymentMethod === 'cash' ? '1010' : '1020'

  // Determine payment description
  const methodLabels: Record<string, string> = {
    bank: 'Bank Transfer', cash: 'Cash Payment',
    upi: 'UPI Transfer', cheque: 'Cheque Payment',
  }
  const methodLabel = methodLabels[input.paymentMethod]
    ?? input.paymentMethod

  const paymentDate = input.paymentDate ?? new Date()

  try {
    // Post journal entry
    // DR 2010 Accounts Payable (reduces what we owe)
    // CR 1010/1020 Cash/Bank (reduces our cash)
    const entry = await createJournalEntry({
      date: paymentDate,
      description: `Vendor payment: ${po.po_number} — ${methodLabel}${input.referenceNumber ? ` (Ref: ${input.referenceNumber})` : ''}`,
      referenceSource: 'PAYMENT',
      referenceId: po.id,
      branchId: po.branch_id!,
      autoGenerated: false,
      createdBy: session.user.id,
      lines: [
        {
          accountCode: '2010',
          debit: input.amount,
          description: `AP settlement: ${po.po_number}`,
        },
        {
          accountCode: paymentAccountCode,
          credit: input.amount,
          description: `${methodLabel} to vendor`,
        },
      ],
    })

    // Record the payment
    const [payment] = await db
      .insert(vendor_payments)
      .values({
        po_id: input.poId,
        vendor_id: po.vendor_id!,
        branch_id: po.branch_id!,
        amount: String(input.amount),
        payment_method: input.paymentMethod,
        reference_number: input.referenceNumber ?? null,
        payment_date: paymentDate,
        notes: input.notes ?? null,
        journal_entry_id: entry.id,
        created_by: session.user.id,
      })
      .returning()

    return { success: true as const, payment, entry }
  } catch (error) {
    console.error('PAYMENT ERROR:', error)
    return {
      success: false as const,
      error: (error as Error).message
    }
  }
}

// ── getVendorPayments ───────────────────────────────

export async function getVendorPayments(input?: {
  poId?: string
  branchId?: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return { success: false as const, error: 'Unauthorized' }
  }

  try {
    const payments = await db
      .select({
        id:              vendor_payments.id,
        poId:            vendor_payments.po_id,
        vendorId:        vendor_payments.vendor_id,
        branchId:        vendor_payments.branch_id,
        amount:          vendor_payments.amount,
        paymentMethod:   vendor_payments.payment_method,
        referenceNumber: vendor_payments.reference_number,
        paymentDate:     vendor_payments.payment_date,
        notes:           vendor_payments.notes,
        createdAt:       vendor_payments.created_at,
        poNumber:        purchase_orders.po_number,
        vendorName:      vendors.name,
      })
      .from(vendor_payments)
      .leftJoin(purchase_orders,
        eq(vendor_payments.po_id, purchase_orders.id))
      .leftJoin(vendors,
        eq(vendor_payments.vendor_id, vendors.id))
      .where(
        input?.poId
          ? eq(vendor_payments.po_id, input.poId)
          : input?.branchId
          ? eq(vendor_payments.branch_id, input.branchId)
          : undefined
      )
      .orderBy(desc(vendor_payments.payment_date))

    return { success: true as const, payments }
  } catch (error) {
    return {
      success: false as const,
      error: (error as Error).message
    }
  }
}

// ── rejectExpense ───────────────────────────────────
export async function rejectExpense(input: { expenseId: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const role = (session.user.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'admin/owner', 'manager'].includes(role)) {
    return { success: false as const, error: 'Manager role required' }
  }

  await db
    .update(expense_records)
    .set({ status: 'rejected' })
    .where(eq(expense_records.id, input.expenseId))

  return { success: true as const }
}

// ── getProfitAndLoss ────────────────────────────────
export async function getProfitAndLoss(input: {
  branchId?: string
  fromDate: string
  toDate: string
  financialYear?: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db.execute(sql`
      SELECT a.code, a.name, a.type,
        COALESCE(SUM(jl.credit - jl.debit), 0) AS net
      FROM accounts a
      LEFT JOIN journal_lines jl ON jl.account_id = a.id
      LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
        AND je.status = 'posted'
        AND je.date >= ${input.fromDate}::timestamp
        AND je.date <= ${input.toDate}::timestamp
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      WHERE a.type IN ('Revenue', 'Expense')
      GROUP BY a.code, a.name, a.type
      ORDER BY a.code
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows
    const revenue  = data.filter(r => r.type === 'Revenue')
    const expenses = data.filter(r => r.type === 'Expense')
    const totalRevenue  = revenue.reduce((s, r)  => s + Number(r.net), 0)
    const totalExpenses = expenses.reduce((s, r) => s + Number(r.net), 0)
    return { success: true as const, revenue, expenses, totalRevenue, totalExpenses, netProfit: totalRevenue - totalExpenses }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getBalanceSheet ─────────────────────────────────
export async function getBalanceSheet(input: { branchId?: string; asOfDate: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db.execute(sql`
      SELECT a.code, a.name, a.type,
        COALESCE(SUM(jl.debit - jl.credit), 0) AS balance
      FROM accounts a
      LEFT JOIN journal_lines jl ON jl.account_id = a.id
      LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
        AND je.status = 'posted'
        AND je.date <= ${input.asOfDate}::timestamp
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      WHERE a.type IN ('Asset', 'Liability', 'Equity')
      GROUP BY a.code, a.name, a.type
      ORDER BY a.code
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows
    return {
      success: true as const,
      assets:      data.filter(r => r.type === 'Asset'),
      liabilities: data.filter(r => r.type === 'Liability'),
      equity:      data.filter(r => r.type === 'Equity'),
    }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getGSTSummary ───────────────────────────────────
export async function getGSTSummary(input: { branchId?: string; fromDate: string; toDate: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db.execute(sql`
      SELECT a.code, a.name,
        COALESCE(SUM(jl.credit), 0) AS collected,
        COALESCE(SUM(jl.debit),  0) AS paid
      FROM accounts a
      LEFT JOIN journal_lines jl ON jl.account_id = a.id
      LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
        AND je.status = 'posted'
        AND je.date >= ${input.fromDate}::timestamp
        AND je.date <= ${input.toDate}::timestamp
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      WHERE a.type = 'Tax'
      GROUP BY a.code, a.name
      ORDER BY a.code
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows
    return { success: true as const, gst: data }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getJournalEntries ───────────────────────────────
export async function getJournalEntries(input?: { branchId?: string; fromDate?: string; toDate?: string; source?: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const entries = await db
      .select({
        id:              journal_entries.id,
        date:            journal_entries.date,
        description:     journal_entries.description,
        referenceSource: journal_entries.reference_source,
        referenceId:     journal_entries.reference_id,
        branchId:        journal_entries.branch_id,
        financialYear:   journal_entries.financial_year,
        status:          journal_entries.status,
        autoGenerated:   journal_entries.auto_generated,
        branchName:      branches.name,
        amount:          sql<number>`(SELECT SUM(debit) FROM journal_lines WHERE journal_entry_id = ${journal_entries.id})`.mapWith(Number),
      })
      .from(journal_entries)
      .leftJoin(branches, eq(journal_entries.branch_id, branches.id))
      .where(input?.branchId ? eq(journal_entries.branch_id, input.branchId) : undefined)
      .orderBy(desc(journal_entries.date))
      .limit(200)

    return { success: true as const, entries }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getExpenses ─────────────────────────────────────
export async function getExpenses(input?: { branchId?: string; status?: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const expenses = await db
      .select()
      .from(expense_records)
      .where(input?.branchId ? eq(expense_records.branch_id, input.branchId) : undefined)
      .orderBy(desc(expense_records.created_at))

    return { success: true as const, expenses }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

export async function getMarginReport(input: {
  branchId?: string
  fromDate: string
  toDate: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return { success: false as const, error: 'Unauthorized' }
  }

  // Only managers and admins can see margin data
  const role = (session.user.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'admin/owner', 'manager']
    .includes(role)) {
    return {
      success: false as const,
      error: 'Manager role required for margin reports'
    }
  }

  try {
    const result = await db.execute(sql`
      SELECT
        p.id AS product_id,
        p.model_name,
        p.brand,
        p.product_code,
        p.base_price AS mrp,
        COUNT(ii.id) AS units_sold,
        SUM(ii.unit_price * ii.qty) AS total_revenue,
        SUM(COALESCE(ii.cost_price, 0) * ii.qty) AS total_cogs,
        SUM(ii.unit_price * ii.qty) -
          SUM(COALESCE(ii.cost_price, 0) * ii.qty)
          AS gross_profit,
        CASE
          WHEN SUM(ii.unit_price * ii.qty) > 0
          THEN (
            (SUM(ii.unit_price * ii.qty) -
             SUM(COALESCE(ii.cost_price, 0) * ii.qty)) /
            SUM(ii.unit_price * ii.qty) * 100
          )
          ELSE 0
        END AS margin_pct,
        SUM(COALESCE(ii.discount_amount, 0)) AS total_discounts,
        COUNT(CASE WHEN ii.approved_by IS NOT NULL
          THEN 1 END) AS manager_approved_discounts
      FROM invoice_items ii
      JOIN sales_invoices si ON si.id = ii.invoice_id
      JOIN products p ON p.id = ii.product_id
      WHERE si.created_at >= ${input.fromDate}::timestamp
        AND si.created_at <= ${input.toDate}::timestamp
        ${input.branchId
          ? sql`AND si.branch_id = ${input.branchId}::uuid`
          : sql``}
      GROUP BY p.id, p.model_name, p.brand,
        p.product_code, p.base_price
      ORDER BY gross_profit DESC
    `)

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (result as any).rows ?? result

    // Calculate totals
    const totalRevenue = data.reduce(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (s: number, r: any) => s + Number(r.total_revenue ?? 0), 0
    )
    const totalCOGS = data.reduce(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (s: number, r: any) => s + Number(r.total_cogs ?? 0), 0
    )
    const totalDiscounts = data.reduce(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (s: number, r: any) => s + Number(r.total_discounts ?? 0), 0
    )

    return {
      success: true as const,
      products: data,
      summary: {
        totalRevenue,
        totalCOGS,
        grossProfit: totalRevenue - totalCOGS,
        overallMarginPct: totalRevenue > 0
          ? ((totalRevenue - totalCOGS) / totalRevenue * 100)
          : 0,
        totalDiscounts,
        totalUnitsSold: data.reduce(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (s: number, r: any) => s + Number(r.units_sold ?? 0), 0
        ),
      },
    }
  } catch (error) {
    return {
      success: false as const,
      error: (error as Error).message
    }
  }
}
