'use server'

import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { db } from '@/db/client'
import {
  accounts, journal_entries, journal_lines,
  expense_records, branches, inventory,
  vendor_payments, purchase_orders, vendors, grn_receipts
} from '@/db/schema'
import { eq, desc, sql, and, or, isNull } from 'drizzle-orm'
import { getEffectiveBranchId } from '@/app/actions/_utils/branch'

// ── Helper: derive Indian financial year ────────────
export async function getFinancialYear(date: Date): Promise<string> {
  const month = date.getMonth() + 1
  const year = date.getFullYear()
  if (month >= 4) return `${year}-${String(year + 1).slice(2)}`
  return `${year - 1}-${String(year).slice(2)}`
}

// ── Helper: resolve account code → id ───────────────
async function getAccountId(code: string, txClient: any = db): Promise<string> {
  const [account] = await db
    .select({ id: accounts.id })
    .from(accounts)
    .where(eq(accounts.code, code))
    .limit(1)
  if (!account) throw new Error(`Account ${code} not found`)
  return account.id
}

// ── Helper: resolve branch-scoped cash account code ─
// Looks for a branch-specific cash account (code like '1010-%' with
// matching branch_id). Falls back to global '1010' for backward
// compatibility when no branch-scoped account exists.
export async function getCashAccountCode(branchId?: string | null): Promise<string> {
  if (!branchId) return '1010'

  const [branchAccount] = await db
    .select({ code: accounts.code })
    .from(accounts)
    .where(
      and(
        sql`${accounts.code} LIKE '1010-%'`,
        eq(accounts.branch_id, branchId),
        eq(accounts.is_active, true),
      )
    )
    .limit(1)

  return branchAccount?.code ?? '1010'
}

// ── createJournalEntry ──────────────────────────────
export async function createJournalEntry(input: {
  date?: Date
  description: string
  referenceSource: string
  referenceId?: string
  branchId: string
  autoGenerated?: boolean
  createdBy: string
  lines: Array<{
    accountCode: string
    debit?: number
    credit?: number
    description?: string
  }>
}) {
  const totalDebit  = input.lines.reduce((s, l) => s + (l.debit  ?? 0), 0)
  const totalCredit = input.lines.reduce((s, l) => s + (l.credit ?? 0), 0)
  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new Error(
      `Journal entry is unbalanced: debits ${totalDebit} ≠ credits ${totalCredit}`
    )
  }

  const date = input.date ?? new Date()
  const financialYear = await getFinancialYear(date)

  const [entry] = await db
    .insert(journal_entries)
    .values({
      date,
      description: input.description,
      reference_source: input.referenceSource,
      reference_id: input.referenceId ?? null,
      branch_id: input.branchId,
      financial_year: financialYear,
      status: 'posted',
      auto_generated: input.autoGenerated ?? false,
      created_by: input.createdBy,
    })
    .returning()

  const lineValues = await Promise.all(
    input.lines.map(async (line) => ({
      journal_entry_id: entry.id,
      account_id: await getAccountId(line.accountCode, db),
      debit:  String(line.debit  ?? 0),
      credit: String(line.credit ?? 0),
      description: line.description ?? null,
    }))
  )

  await db.insert(journal_lines).values(lineValues)
  return entry
}

// ── postGRNJournal ──────────────────────────────────
// DR 1040 Inventory Asset, DR 1050 GST ITC (CGST/SGST/IGST), CR 2010 Payable
export async function postGRNJournal(input: {
  grnId: string
  poId: string
  branchId: string
  createdBy: string
  totalLandedCost: number
  totalCGST: number
  totalSGST: number
  totalIGST: number
}) {
  const totalGST = input.totalCGST + input.totalSGST + input.totalIGST
  const totalPayable = input.totalLandedCost + totalGST

  const [grn] = await db
    .select({ grnNumber: grn_receipts.grn_number })
    .from(grn_receipts)
    .where(eq(grn_receipts.id, input.grnId))
    .limit(1)

  const [po] = await db
    .select({ poNumber: purchase_orders.po_number })
    .from(purchase_orders)
    .where(eq(purchase_orders.id, input.poId))
    .limit(1)

  const grnRef = grn?.grnNumber ?? input.grnId
  const poRef = po?.poNumber ?? input.poId

  const lines: Array<{
    accountCode: string
    debit?: number
    credit?: number
    description: string
  }> = []

  lines.push({
    accountCode: '1040',
    debit: input.totalLandedCost,
    description: `Inventory received — ${grnRef}`,
  })

  if (input.totalCGST > 0) {
    lines.push({
      accountCode: '1051',
      debit: input.totalCGST,
      description: `CGST Input Tax Credit — ${grnRef}`,
    })
  }

  if (input.totalSGST > 0) {
    lines.push({
      accountCode: '1052',
      debit: input.totalSGST,
      description: `SGST Input Tax Credit — ${grnRef}`,
    })
  }

  if (input.totalIGST > 0) {
    lines.push({
      accountCode: '1053',
      debit: input.totalIGST,
      description: `IGST Input Tax Credit — ${grnRef}`,
    })
  }

  lines.push({
    accountCode: '2010',
    credit: totalPayable,
    description: `Payable to vendor — ${poRef}`,
  })

  await createJournalEntry({
    description: `GRN: ${grnRef} (against ${poRef}) — ₹${input.totalLandedCost.toLocaleString('en-IN')} + GST ₹${totalGST.toLocaleString('en-IN')}`,
    referenceSource: 'GRN',
    referenceId: input.grnId,
    branchId: input.branchId,
    autoGenerated: true,
    createdBy: input.createdBy,
    lines,
  })
}

// ── postSalesJournal ────────────────────────────────
// DR 1010 Cash, CR 4000 Revenue, CR GST Payable, DR 5010 COGS, CR 1040 Inventory
export async function postSalesJournal(input: {
  invoiceId: string
  branchId: string
  createdBy: string
  saleTotal: number
  subtotal: number
  cgst: number
  sgst: number
  igst: number
  cogs: number
  loyaltyDiscountAmount?: number
}) {
  // If cogs not provided, calculate from inventory
  let cogsAmount = input.cogs

  if (cogsAmount === 0 && input.invoiceId) {
    try {
      const soldUnits = await db
        .select({ landedCost: inventory.landed_cost })
        .from(inventory)
        .where(eq(inventory.invoice_id, input.invoiceId))

      cogsAmount = soldUnits.reduce(
        (sum, unit) => sum + Number(unit.landedCost ?? 0),
        0
      )
    } catch {
      // If lookup fails, COGS stays 0 — don't block journal
      cogsAmount = 0
    }
  }

  const netReceived = input.saleTotal - (input.loyaltyDiscountAmount ?? 0)
  const cashCode = await getCashAccountCode(input.branchId)

  const lines: Array<{ accountCode: string; debit?: number; credit?: number; description?: string }> = [
    { accountCode: cashCode, debit: netReceived, description: 'Cash received from POS sale' },
    { accountCode: '4000', credit: input.subtotal, description: 'Sales revenue ex-tax' },
  ]
  
  if (input.loyaltyDiscountAmount && input.loyaltyDiscountAmount > 0) {
    // Loyalty redemption: reduce the Loyalty Liability we owe the customer.
    // DR 2050 Loyalty Liability  — we owed them this; now it's settled
    // The cash line already credits only netReceived, so the liability
    // debit here completes the balance.
    lines.push({
      accountCode: '2050',
      debit: input.loyaltyDiscountAmount,
      description: 'Loyalty liability settled — points redeemed',
    })
  }

  if (input.cgst > 0) lines.push({ accountCode: '2020', credit: input.cgst, description: 'CGST collected' })
  if (input.sgst > 0) lines.push({ accountCode: '2030', credit: input.sgst, description: 'SGST collected' })
  if (input.igst > 0) lines.push({ accountCode: '2040', credit: input.igst, description: 'IGST collected' })

  if (cogsAmount > 0) {
    lines.push(
      { accountCode: '5010', debit: cogsAmount,  description: 'Cost of goods sold' },
      { accountCode: '1040', credit: cogsAmount, description: 'Inventory asset reduced' }
    )
  }

  await createJournalEntry({
    description: 'Auto: POS sale invoice',
    referenceSource: 'SALES',
    referenceId: input.invoiceId,
    branchId: input.branchId,
    autoGenerated: true,
    createdBy: input.createdBy,
    lines,
  })
}

// ── postDebitNoteJournal ────────────────────────────
// Reverse of postGRNJournal: DR 2010 AP (reduce payable), CR 1040 Inventory,
// CR 1051/1052/1053 ITC reversal. Used when returning goods to vendor.
export async function postDebitNoteJournal(input: {
  debitNoteId: string
  debitNoteNumber: string
  poId: string
  branchId: string
  createdBy: string
  totalLandedCost: number
  totalCGST: number
  totalSGST: number
  totalIGST: number
}) {
  const totalGST = input.totalCGST + input.totalSGST + input.totalIGST
  const totalDebit = input.totalLandedCost + totalGST

  const [po] = await db
    .select({ poNumber: purchase_orders.po_number })
    .from(purchase_orders)
    .where(eq(purchase_orders.id, input.poId))
    .limit(1)

  const poRef = po?.poNumber ?? input.poId
  const dnRef = input.debitNoteNumber

  const lines: Array<{
    accountCode: string
    debit?: number
    credit?: number
    description: string
  }> = []

  lines.push({
    accountCode: '2010',
    debit: totalDebit,
    description: `AP reduction — Debit Note ${dnRef} / ${poRef}`,
  })

  lines.push({
    accountCode: '1040',
    credit: input.totalLandedCost,
    description: `Inventory cost reversal — ${dnRef}`,
  })

  if (input.totalCGST > 0) {
    lines.push({
      accountCode: '1051',
      credit: input.totalCGST,
      description: `CGST ITC reversal — ${dnRef}`,
    })
  }

  if (input.totalSGST > 0) {
    lines.push({
      accountCode: '1052',
      credit: input.totalSGST,
      description: `SGST ITC reversal — ${dnRef}`,
    })
  }

  if (input.totalIGST > 0) {
    lines.push({
      accountCode: '1053',
      credit: input.totalIGST,
      description: `IGST ITC reversal — ${dnRef}`,
    })
  }

  await createJournalEntry({
    description: `Debit Note: ${dnRef} (${poRef}) — ₹${totalDebit.toLocaleString('en-IN')} reversed`,
    referenceSource: 'DEBIT_NOTE',
    referenceId: input.debitNoteId,
    branchId: input.branchId,
    autoGenerated: true,
    createdBy: input.createdBy,
    lines,
  })
}

// ── createExpenseRecord ─────────────────────────────
export async function createExpenseRecord(input: {
  amount: number
  expenseAccount: string
  paymentAccount?: string
  description: string
  receiptUrl?: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const branchId = await getEffectiveBranchId(session)
  if (!branchId) return { success: false as const, error: 'No branch selected' }

  if (input.amount <= 0) return { success: false as const, error: 'Amount must be greater than 0' }

  // Resolve the payment account: use branch-scoped cash if no explicit override
  const resolvedPaymentAccount = input.paymentAccount ?? await getCashAccountCode(branchId)

  try {
    await getAccountId(input.expenseAccount)
    await getAccountId(resolvedPaymentAccount)
  } catch (e) {
    return { success: false as const, error: (e as Error).message }
  }

  const [record] = await db
    .insert(expense_records)
    .values({
      branch_id:       branchId,
      created_by:      session.user.id,
      amount:          String(input.amount),
      expense_account: input.expenseAccount,
      payment_account: resolvedPaymentAccount,
      description:     input.description,
      receipt_url:     input.receiptUrl ?? null,
      status:          'pending',
    })
    .returning()

  return { success: true as const, record }
}

// ── approveExpense ──────────────────────────────────
export async function approveExpense(input: { expenseId: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const role = (session.user.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'admin/owner', 'manager'].includes(role)) {
    return { success: false as const, error: 'Manager role required' }
  }

  const [expense] = await db
    .select()
    .from(expense_records)
    .where(eq(expense_records.id, input.expenseId))
    .limit(1)

  if (!expense) return { success: false as const, error: 'Expense not found' }
  if (expense.status !== 'pending') {
    return { success: false as const, error: `Cannot approve expense with status: ${expense.status}` }
  }

  // If the stored payment_account is the legacy global '1010', resolve it
  // to the branch-scoped cash account for proper branch-level tracking.
  let resolvedPaymentAccount = expense.payment_account
  if (resolvedPaymentAccount === '1010') {
    resolvedPaymentAccount = await getCashAccountCode(expense.branch_id)
  }

  const entry = await createJournalEntry({
    description: `Expense: ${expense.description}`,
    referenceSource: 'EXPENSE',
    referenceId: expense.id,
    branchId: expense.branch_id,
    autoGenerated: false,
    createdBy: session.user.id,
    lines: [
      { accountCode: expense.expense_account, debit: Number(expense.amount), description: expense.description },
      { accountCode: resolvedPaymentAccount, credit: Number(expense.amount), description: 'Payment from cash/bank' },
    ],
  })

  await db
    .update(expense_records)
    .set({ status: 'approved', approved_by: session.user.id, approved_at: new Date(), journal_entry_id: entry.id })
    .where(eq(expense_records.id, input.expenseId))

  return { success: true as const, entry }
}

export async function settleVendorPayment(input: {
  poId: string
  amount: number
  paymentMethod: string  // bank|cash|upi|cheque
  referenceNumber?: string
  notes?: string
  paymentDate?: Date
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return { success: false as const, error: 'Unauthorized' }
  }

  const role = (session.user.role ?? '').toLowerCase()
  const isManager = ['admin', 'super_admin', 'admin/owner',
    'manager'].includes(role)
  if (!isManager) {
    return {
      success: false as const,
      error: 'Manager role required to record payments'
    }
  }

  if (input.amount <= 0) {
    return {
      success: false as const,
      error: 'Payment amount must be greater than 0'
    }
  }

  // Get PO with vendor info
  const [po] = await db
    .select({
      id: purchase_orders.id,
      po_number: purchase_orders.po_number,
      vendor_id: purchase_orders.vendor_id,
      branch_id: purchase_orders.branch_id,
      total_amount: purchase_orders.total_amount,
      status: purchase_orders.status,
    })
    .from(purchase_orders)
    .where(eq(purchase_orders.id, input.poId))
    .limit(1)

  if (!po) {
    return { success: false as const, error: 'PO not found' }
  }

  // Only settled/received POs can be paid — check before AP query
  const payableStatuses = [
    'received', 'partially_received',
    'approved', 'PARTIALLY_RETURNED', 'RETURNED'
  ]
  if (!payableStatuses.includes(po.status ?? '')) {
    return {
      success: false as const,
      error: `Cannot record payment for PO with status: ${po.status}`
    }
  }

  // Derive outstanding AP from journal lines on account 2010 for this PO.
  // Net AP = SUM(credit) - SUM(debit) across all posted journal entries
  // referencing this PO. This correctly reflects:
  //   + GRN journals      (CR 2010 = amount owed)
  //   - Debit notes       (DR 2010 = AP reduced)
  //   - Short-close reversals (DR 2010 = AP reduced)
  //   - Prior vendor payments (DR 2010 = AP settled)
  const apBalanceResult = await db.execute(sql`
    SELECT
      COALESCE(SUM(jl.credit), 0) AS total_cr,
      COALESCE(SUM(jl.debit),  0) AS total_dr
    FROM journal_lines jl
    JOIN journal_entries je
      ON je.id = jl.journal_entry_id
    JOIN accounts a
      ON a.id = jl.account_id
    WHERE je.reference_id = ${input.poId}
      AND je.status = 'posted'
      AND a.code = '2010'
  `)

  const apRows = (apBalanceResult as any).rows ?? apBalanceResult
  const totalCR = Number(apRows[0]?.total_cr ?? 0)
  const totalDR = Number(apRows[0]?.total_dr ?? 0)
  const remainingBalance = Number((totalCR - totalDR).toFixed(2))

  if (remainingBalance <= 0) {
    return {
      success: false as const,
      error: `No outstanding AP balance for this PO — already fully settled or reversed`,
    }
  }

  if (input.amount > remainingBalance + 0.01) {
    return {
      success: false as const,
      error: `Payment ₹${input.amount.toLocaleString('en-IN')} exceeds outstanding AP balance ₹${remainingBalance.toLocaleString('en-IN')}`,
    }
  }

  // Determine payment account from method — branch-scoped cash if applicable
  const paymentAccountCode =
    input.paymentMethod === 'cash' ? await getCashAccountCode(po.branch_id) : '1020'

  // Determine payment description
  const methodLabels: Record<string, string> = {
    bank: 'Bank Transfer', cash: 'Cash Payment',
    upi: 'UPI Transfer', cheque: 'Cheque Payment',
  }
  const methodLabel = methodLabels[input.paymentMethod]
    ?? input.paymentMethod

  const paymentDate = input.paymentDate ?? new Date()

  try {
    // Post journal entry
    // DR 2010 Accounts Payable (reduces what we owe)
    // CR 1010/1020 Cash/Bank (reduces our cash)
    const entry = await createJournalEntry({
      date: paymentDate,
      description: `Vendor payment: ${po.po_number} — ${methodLabel}${input.referenceNumber ? ` (Ref: ${input.referenceNumber})` : ''}`,
      referenceSource: 'PAYMENT',
      referenceId: po.id,
      branchId: po.branch_id!,
      autoGenerated: false,
      createdBy: session.user.id,
      lines: [
        {
          accountCode: '2010',
          debit: input.amount,
          description: `AP settlement: ${po.po_number}`,
        },
        {
          accountCode: paymentAccountCode,
          credit: input.amount,
          description: `${methodLabel} to vendor`,
        },
      ],
    })

    // Record the payment
    const [payment] = await db
      .insert(vendor_payments)
      .values({
        po_id: input.poId,
        vendor_id: po.vendor_id!,
        branch_id: po.branch_id!,
        amount: String(input.amount),
        payment_method: input.paymentMethod,
        reference_number: input.referenceNumber ?? null,
        payment_date: paymentDate,
        notes: input.notes ?? null,
        journal_entry_id: entry.id,
        created_by: session.user.id,
      })
      .returning()

    return { success: true as const, payment, entry }
  } catch (error) {
    console.error('PAYMENT ERROR:', error)
    return {
      success: false as const,
      error: (error as Error).message
    }
  }
}

// ── getVendorPayments ───────────────────────────────

export async function getVendorPayments(input?: {
  poId?: string
  branchId?: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return { success: false as const, error: 'Unauthorized' }
  }

  try {
    const payments = await db
      .select({
        id:              vendor_payments.id,
        poId:            vendor_payments.po_id,
        vendorId:        vendor_payments.vendor_id,
        branchId:        vendor_payments.branch_id,
        amount:          vendor_payments.amount,
        paymentMethod:   vendor_payments.payment_method,
        referenceNumber: vendor_payments.reference_number,
        paymentDate:     vendor_payments.payment_date,
        notes:           vendor_payments.notes,
        createdAt:       vendor_payments.created_at,
        poNumber:        purchase_orders.po_number,
        vendorName:      vendors.name,
      })
      .from(vendor_payments)
      .leftJoin(purchase_orders,
        eq(vendor_payments.po_id, purchase_orders.id))
      .leftJoin(vendors,
        eq(vendor_payments.vendor_id, vendors.id))
      .where(
        input?.poId
          ? eq(vendor_payments.po_id, input.poId)
          : input?.branchId
          ? eq(vendor_payments.branch_id, input.branchId)
          : undefined
      )
      .orderBy(desc(vendor_payments.payment_date))

    return { success: true as const, payments }
  } catch (error) {
    return {
      success: false as const,
      error: (error as Error).message
    }
  }
}

// ── rejectExpense ───────────────────────────────────
export async function rejectExpense(input: { expenseId: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const role = (session.user.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'admin/owner', 'manager'].includes(role)) {
    return { success: false as const, error: 'Manager role required' }
  }

  await db
    .update(expense_records)
    .set({ status: 'rejected' })
    .where(eq(expense_records.id, input.expenseId))

  return { success: true as const }
}

// ── getProfitAndLoss ────────────────────────────────
export async function getProfitAndLoss(input: {
  branchId?: string
  fromDate: string
  toDate: string
  financialYear?: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db.execute(sql`
      SELECT a.code, a.name, a.type,
        COALESCE(SUM(jl.credit - jl.debit), 0) AS net
      FROM accounts a
      LEFT JOIN journal_lines jl ON jl.account_id = a.id
      LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
        AND je.status = 'posted'
        AND je.date >= ${input.fromDate}::timestamp
        AND je.date <= ${input.toDate}::timestamp
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      WHERE a.type IN ('Revenue', 'Expense')
      GROUP BY a.code, a.name, a.type
      ORDER BY a.code
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows
    const revenue  = data.filter(r => r.type === 'Revenue')
    const expenses = data.filter(r => r.type === 'Expense')
    const totalRevenue  = revenue.reduce((s, r)  => s + Number(r.net), 0)
    const totalExpenses = expenses.reduce((s, r) => s + Number(r.net), 0)
    // expenses.net is already negative (credit - debit), so addition is correct
    return { success: true as const, revenue, expenses, totalRevenue, totalExpenses, netProfit: totalRevenue + totalExpenses }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getBalanceSheet ─────────────────────────────────
export async function getBalanceSheet(input: { branchId?: string; asOfDate: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    // 1. Fetch all BS accounts (Asset, Liability, Equity, Tax)
    const rows = await db.execute(sql`
      SELECT a.code, a.name, a.type,
        COALESCE(SUM(jl.debit - jl.credit), 0) AS balance
      FROM accounts a
      LEFT JOIN journal_lines jl ON jl.account_id = a.id
      LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
        AND je.status = 'posted'
        AND je.date <= ${input.asOfDate}::timestamp
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      WHERE a.type IN ('Asset', 'Liability', 'Equity', 'Tax')
        AND a.is_active = true
      GROUP BY a.code, a.name, a.type
      ORDER BY a.code
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows

    // 2. Compute Net Profit from Revenue/Expense accounts for the same period.
    //    Net Profit = SUM(credit - debit) across Revenue + Expense accounts.
    //    This gives a positive number when profitable (revenue credits > expense debits).
    const plRows = await db.execute(sql`
      SELECT COALESCE(SUM(jl.credit - jl.debit), 0) AS net_profit
      FROM journal_lines jl
      JOIN journal_entries je ON je.id = jl.journal_entry_id
        AND je.status = 'posted'
        AND je.date <= ${input.asOfDate}::timestamp
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      JOIN accounts a ON a.id = jl.account_id
      WHERE a.type IN ('Revenue', 'Expense')
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const plData: any[] = (plRows as any).rows ?? plRows
    const netProfit = Number(plData[0]?.net_profit ?? 0)

    // 3. Inject Net Profit into Retained Earnings (3010).
    //    In DR-CR convention, equity is credit-natural so a profit (positive in
    //    credit-debit) becomes negative in debit-credit. We subtract netProfit
    //    from the 3010 balance to add the equity.
    const equity = data.filter(r => r.type === 'Equity').map(r => {
      if (r.code === '3010') {
        return { ...r, balance: String(Number(r.balance) - netProfit) }
      }
      return r
    })

    // If 3010 doesn't exist in data (no journal lines yet), inject it
    if (!equity.find(r => r.code === '3010') && netProfit !== 0) {
      equity.push({
        code: '3010',
        name: 'Retained Earnings',
        type: 'Equity',
        balance: String(-netProfit),
      })
      equity.sort((a: { code: string }, b: { code: string }) => a.code.localeCompare(b.code))
    }

    // 4. Tax accounts sorted by balance direction
    const taxRows = data.filter(r => r.type === 'Tax')
    const taxAssets = taxRows.filter(r => Number(r.balance) >= 0)
    const taxLiabilities = taxRows.filter(r => Number(r.balance) < 0)

    return {
      success: true as const,
      assets:      [...data.filter(r => r.type === 'Asset'), ...taxAssets],
      liabilities: [...data.filter(r => r.type === 'Liability'), ...taxLiabilities],
      equity,
      netProfit,
    }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getGSTSummary ───────────────────────────────────
export async function getGSTSummary(input: { branchId?: string; fromDate: string; toDate: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db.execute(sql`
      SELECT a.code, a.name,
        COALESCE(SUM(jl.credit), 0) AS collected,
        COALESCE(SUM(jl.debit),  0) AS paid
      FROM accounts a
      LEFT JOIN journal_lines jl ON jl.account_id = a.id
      LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
        AND je.status = 'posted'
        AND je.date >= ${input.fromDate}::timestamp
        AND je.date <= ${input.toDate}::timestamp
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      WHERE a.type = 'Tax'
      GROUP BY a.code, a.name
      ORDER BY a.code
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows
    return { success: true as const, gst: data }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getJournalEntries ───────────────────────────────
// Supports keyset (cursor) pagination: pass cursor.lastDate + cursor.lastId
// from the previous batch to fetch the next page. Returns hasMore + nextCursor
// so the frontend knows when to stop.
const JOURNAL_PAGE_SIZE = 50

export async function getJournalEntries(input?: {
  branchId?: string
  fromDate?: string
  toDate?: string
  source?: string
  cursor?: { lastDate: string; lastId: string }
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    // Single query with LEFT JOIN + GROUP BY (B9 fix).
    // Keyset pagination condition: fetch rows strictly "before" the cursor
    // in the (date DESC, id DESC) sort order (B8 fix).
    const rows = await db.execute(sql`
      SELECT
        je.id,
        je.date,
        je.description,
        je.reference_source   AS "referenceSource",
        je.reference_id       AS "referenceId",
        je.branch_id          AS "branchId",
        je.financial_year      AS "financialYear",
        je.status,
        je.auto_generated      AS "autoGenerated",
        je.edited_at           AS "editedAt",
        je.edit_reason         AS "editReason",
        b.name                AS "branchName",
        COALESCE(SUM(jl.debit), 0)::numeric AS amount
      FROM journal_entries je
      LEFT JOIN branches b ON b.id = je.branch_id
      LEFT JOIN journal_lines jl ON jl.journal_entry_id = je.id
      WHERE 1 = 1
        ${input?.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
        ${input?.fromDate ? sql`AND je.date >= ${input.fromDate}::timestamp` : sql``}
        ${input?.toDate ? sql`AND je.date <= ${input.toDate}::timestamp + interval '1 day' - interval '1 second'` : sql``}
        ${input?.cursor?.lastDate && input?.cursor?.lastId
          ? sql`AND (je.date < ${input.cursor.lastDate}::timestamp OR (je.date = ${input.cursor.lastDate}::timestamp AND je.id < ${input.cursor.lastId}::uuid))`
          : sql``}
      GROUP BY je.id, b.name
      ORDER BY je.date DESC, je.id DESC
      LIMIT ${JOURNAL_PAGE_SIZE + 1}
    `)

    // Normalise the pg result shape (rows array)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows

    // If we got PAGE_SIZE+1 rows, there are more pages
    const hasMore = data.length > JOURNAL_PAGE_SIZE
    const page = hasMore ? data.slice(0, JOURNAL_PAGE_SIZE) : data

    const entries = page.map((r) => ({
      id:              r.id,
      date:            r.date,
      description:     r.description,
      referenceSource: r.referenceSource,
      referenceId:     r.referenceId,
      branchId:        r.branchId,
      financialYear:   r.financialYear,
      status:          r.status,
      autoGenerated:   r.autoGenerated,
      branchName:      r.branchName,
      amount:          Number(r.amount ?? 0),
    }))

    // Build cursor for the next page from the last entry in this batch
    const lastEntry = entries[entries.length - 1]
    const nextCursor = lastEntry
      ? { lastDate: new Date(lastEntry.date).toISOString(), lastId: lastEntry.id }
      : undefined

    return { success: true as const, entries, hasMore, nextCursor }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── exportJournalLedger (B11: audit-ready CSV data) ─
// Returns a FLAT array where every journal_line is its own row — not
// aggregated. Designed for CSV export / audit files.
export async function exportJournalLedger(input: {
  branchId?: string
  fromDate: string
  toDate: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db.execute(sql`
      SELECT
        je.date                          AS "entryDate",
        je.reference_source              AS "source",
        je.reference_id                  AS "referenceId",
        je.description                   AS "entryDescription",
        b.name                           AS "branchName",
        a.code                           AS "accountCode",
        a.name                           AS "accountName",
        jl.description                   AS "lineDescription",
        jl.debit::numeric                AS debit,
        jl.credit::numeric               AS credit
      FROM journal_entries je
      INNER JOIN journal_lines jl ON jl.journal_entry_id = je.id
      INNER JOIN accounts a      ON a.id = jl.account_id
      LEFT  JOIN branches b      ON b.id = je.branch_id
      WHERE je.date >= ${input.fromDate}::timestamp
        AND je.date <= ${input.toDate}::timestamp + interval '1 day' - interval '1 second'
        ${input.branchId ? sql`AND je.branch_id = ${input.branchId}::uuid` : sql``}
      ORDER BY je.date DESC, je.id, jl.debit DESC NULLS LAST, a.code ASC
    `)

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows
    const lines = data.map((r) => ({
      entryDate:        r.entryDate,
      source:           r.source,
      referenceId:      r.referenceId ?? '',
      entryDescription: r.entryDescription,
      branchName:       r.branchName ?? '',
      accountCode:      r.accountCode,
      accountName:      r.accountName,
      lineDescription:  r.lineDescription ?? '',
      debit:            Number(r.debit ?? 0),
      credit:           Number(r.credit ?? 0),
    }))

    return { success: true as const, lines }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getJournalLines (B10: drill-down) ───────────────
// Returns the individual debit/credit lines for a single journal entry.
// Called on-demand from the frontend when the user expands a row.
export async function getJournalLines(input: { journalEntryId: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db.execute(sql`
      SELECT
        jl.journal_line_id AS id,
        a.code              AS "accountCode",
        a.name              AS "accountName",
        a.type              AS "accountType",
        jl.debit::numeric   AS debit,
        jl.credit::numeric  AS credit,
        jl.description
      FROM journal_lines jl
      INNER JOIN accounts a ON a.id = jl.account_id
      WHERE jl.journal_entry_id = ${input.journalEntryId}::uuid
      ORDER BY jl.debit DESC NULLS LAST, a.code ASC
    `)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (rows as any).rows ?? rows
    const lines = data.map((r) => ({
      id:          r.id,
      accountCode: r.accountCode,
      accountName: r.accountName,
      accountType: r.accountType,
      debit:       Number(r.debit ?? 0),
      credit:      Number(r.credit ?? 0),
      description: r.description ?? '',
    }))
    return { success: true as const, lines }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getExpenses ─────────────────────────────────────
export async function getExpenses(input?: { branchId?: string; status?: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const conditions = []
    if (input?.branchId) {
      conditions.push(eq(expense_records.branch_id, input.branchId))
    }
    if (input?.status) {
      conditions.push(eq(expense_records.status, input.status))
    }

    const expenses = await db
      .select()
      .from(expense_records)
      .where(conditions.length > 0
        ? conditions.length === 1
          ? conditions[0]
          : and(...conditions)
        : undefined)
      .orderBy(desc(expense_records.created_at))

    return { success: true as const, expenses }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

export async function getMarginReport(input: {
  branchId?: string
  fromDate: string
  toDate: string
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return { success: false as const, error: 'Unauthorized' }
  }

  // Only managers and admins can see margin data
  const role = (session.user.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'admin/owner', 'manager']
    .includes(role)) {
    return {
      success: false as const,
      error: 'Manager role required for margin reports'
    }
  }

  try {
    const result = await db.execute(sql`
      SELECT
        p.id AS product_id,
        p.model_name,
        p.brand,
        p.product_code,
        p.base_price AS mrp,
        COUNT(ii.id) AS units_sold,
        SUM(ii.unit_price * ii.qty) AS total_revenue,
        SUM(COALESCE(ii.cost_price, 0) * ii.qty) AS total_cogs,
        SUM(ii.unit_price * ii.qty) -
          SUM(COALESCE(ii.cost_price, 0) * ii.qty)
          AS gross_profit,
        CASE
          WHEN SUM(ii.unit_price * ii.qty) > 0
          THEN (
            (SUM(ii.unit_price * ii.qty) -
             SUM(COALESCE(ii.cost_price, 0) * ii.qty)) /
            SUM(ii.unit_price * ii.qty) * 100
          )
          ELSE 0
        END AS margin_pct,
        SUM(COALESCE(ii.discount_amount, 0)) AS total_discounts,
        COUNT(CASE WHEN ii.approved_by IS NOT NULL
          THEN 1 END) AS manager_approved_discounts
      FROM invoice_items ii
      JOIN sales_invoices si ON si.id = ii.invoice_id
      JOIN products p ON p.id = ii.product_id
      WHERE si.created_at >= ${input.fromDate}::timestamp
        AND si.created_at <= ${input.toDate}::timestamp
        ${input.branchId
          ? sql`AND si.branch_id = ${input.branchId}::uuid`
          : sql``}
      GROUP BY p.id, p.model_name, p.brand,
        p.product_code, p.base_price
      ORDER BY gross_profit DESC
    `)

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[] = (result as any).rows ?? result

    // Calculate totals
    const totalRevenue = data.reduce(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (s: number, r: any) => s + Number(r.total_revenue ?? 0), 0
    )
    const totalCOGS = data.reduce(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (s: number, r: any) => s + Number(r.total_cogs ?? 0), 0
    )
    const totalDiscounts = data.reduce(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (s: number, r: any) => s + Number(r.total_discounts ?? 0), 0
    )

    return {
      success: true as const,
      products: data,
      summary: {
        totalRevenue,
        totalCOGS,
        grossProfit: totalRevenue - totalCOGS,
        overallMarginPct: totalRevenue > 0
          ? ((totalRevenue - totalCOGS) / totalRevenue * 100)
          : 0,
        totalDiscounts,
        totalUnitsSold: data.reduce(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (s: number, r: any) => s + Number(r.units_sold ?? 0), 0
        ),
      },
    }
  } catch (error) {
    return {
      success: false as const,
      error: (error as Error).message
    }
  }
}

// ── getActiveAccounts ───────────────────────────────
// Returns active Chart of Accounts entries filtered by branch scope.
// Pass input.branchId to override the session-derived branch (e.g. admin
// selecting a specific branch in ManualJournalDrawer).
// Global accounts (branch_id IS NULL) are always included.
export async function getActiveAccounts(input?: { branchId?: string }) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const role = (session.user.role ?? '').toLowerCase()
  const isSuperAdmin = ['admin', 'super_admin', 'admin/owner'].includes(role)

  try {
    // Explicit branchId overrides session; fall back to session branch for non-admins
    let filterBranchId: string | undefined = input?.branchId
    if (!filterBranchId && !isSuperAdmin) {
      filterBranchId = await getEffectiveBranchId(session) ?? undefined
    }

    const rows = await db
      .select({
        id: accounts.id,
        code: accounts.code,
        name: accounts.name,
        type: accounts.type,
      })
      .from(accounts)
      .where(
        and(
          eq(accounts.is_active, true),
          filterBranchId
            ? or(isNull(accounts.branch_id), eq(accounts.branch_id, filterBranchId))
            : isSuperAdmin
            ? undefined   // admin with no branch override: show all accounts
            : undefined,  // non-admin with no branch: show all (fallback, shouldn't occur)
        )
      )
      .orderBy(accounts.code)

    return { success: true as const, accounts: rows }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getBranches ─────────────────────────────────────
export async function getBranches() {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  try {
    const rows = await db
      .select({ id: branches.id, name: branches.name })
      .from(branches)
      .orderBy(branches.name)
    return { success: true as const, branches: rows }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── createManualJournal ─────────────────────────────
// Allows managers/admins to post adjusting entries such as
// opening balances, corrections, or year-end closings.
export async function createManualJournal(input: {
  date: string
  description: string
  branchId: string
  lines: Array<{ accountCode: string; debit?: number; credit?: number; description?: string }>
}) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return { success: false as const, error: 'Unauthorized' }

  const role = (session.user.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'admin/owner', 'manager'].includes(role)) {
    return { success: false as const, error: 'Manager role required to post manual journal entries' }
  }

  if (!input.lines || input.lines.length < 2) {
    return { success: false as const, error: 'A journal entry must have at least 2 lines' }
  }

  if (!input.description?.trim()) {
    return { success: false as const, error: 'Description (narration) is required' }
  }

  // Strict double-entry validation: total debits must equal total credits
  const totalDebits  = input.lines.reduce((s, l) => s + (l.debit  ?? 0), 0)
  const totalCredits = input.lines.reduce((s, l) => s + (l.credit ?? 0), 0)

  if (Math.abs(totalDebits - totalCredits) > 0.01) {
    return {
      success: false as const,
      error: `Debits (₹${totalDebits.toFixed(2)}) must equal Credits (₹${totalCredits.toFixed(2)})`
    }
  }

  // Validate that each line has either a debit or credit (not both, not neither)
  for (const line of input.lines) {
    const d = line.debit ?? 0
    const c = line.credit ?? 0
    if (d === 0 && c === 0) {
      return { success: false as const, error: `Line for account ${line.accountCode} has neither debit nor credit` }
    }
    if (d > 0 && c > 0) {
      return { success: false as const, error: `Line for account ${line.accountCode} cannot have both debit and credit` }
    }
  }

  try {
    const entry = await createJournalEntry({
      date: new Date(input.date),
      description: input.description.trim(),
      referenceSource: 'MANUAL',
      branchId: input.branchId,
      autoGenerated: false,
      createdBy: session.user.id,
      lines: input.lines,
    })

    return { success: true as const, entry }
  } catch (error) {
    return { success: false as const, error: (error as Error).message }
  }
}

// ── getAPBalanceForPO ───────────────────────────────
export async function getAPBalanceForPO(input: {
  poId: string
}): Promise<{
  success: boolean
  outstandingBalance?: number
  totalCharged?: number
  totalReversed?: number
  totalPaid?: number
  error?: string
}> {
  const session = await getServerSession(authOptions)
  if (!session?.user) {
    return { success: false, error: 'Unauthorized' }
  }

  try {
    const result = await db.execute(sql`
      SELECT
        COALESCE(SUM(jl.credit), 0) AS total_cr,
        COALESCE(SUM(jl.debit),  0) AS total_dr,
        COALESCE(SUM(
          CASE WHEN je.reference_source = 'GRN'
          THEN jl.credit ELSE 0 END
        ), 0) AS total_charged,
        COALESCE(SUM(
          CASE WHEN je.reference_source IN ('DEBIT_NOTE', 'SHORT_CLOSE')
          THEN jl.debit ELSE 0 END
        ), 0) AS total_reversed,
        COALESCE(SUM(
          CASE WHEN je.reference_source = 'PAYMENT'
          THEN jl.debit ELSE 0 END
        ), 0) AS total_paid
      FROM journal_lines jl
      JOIN journal_entries je
        ON je.id = jl.journal_entry_id
      JOIN accounts a
        ON a.id = jl.account_id
      WHERE je.reference_id = ${input.poId}
        AND je.status = 'posted'
        AND a.code = '2010'
    `)

    const rows = (result as any).rows ?? result
    const totalCR       = Number(rows[0]?.total_cr      ?? 0)
    const totalDR       = Number(rows[0]?.total_dr      ?? 0)
    const totalCharged  = Number(rows[0]?.total_charged  ?? 0)
    const totalReversed = Number(rows[0]?.total_reversed ?? 0)
    const totalPaid     = Number(rows[0]?.total_paid     ?? 0)

    return {
      success: true,
      outstandingBalance: Number((totalCR - totalDR).toFixed(2)),
      totalCharged,
      totalReversed,
      totalPaid,
    }
  } catch (error) {
    return { success: false, error: (error as Error).message }
  }
}

// ── editJournalEntry (Secure Audit Edit) ────────────
export async function editJournalEntry(input: {
  id: string
  description: string
  editReason: string
  lines: Array<{
    accountCode: string
    debit?: number
    credit?: number
    description?: string
  }>
}) {
  const session = await getServerSession(authOptions)
  const role = session?.user?.role?.toLowerCase()
  if (!session?.user?.id || (role !== 'admin' && role !== 'owner' && role !== 'admin/owner' && role !== 'super_admin')) {
    return { success: false, error: "Unauthorized: Only Admins or Owners can edit journal entries." }
  }

  const totalDebit = input.lines.reduce((s, l) => s + (l.debit ?? 0), 0)
  const totalCredit = input.lines.reduce((s, l) => s + (l.credit ?? 0), 0)
  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    return { success: false, error: `Journal entry is unbalanced: debits ${totalDebit} ≠ credits ${totalCredit}` }
  }

  if (!input.editReason || input.editReason.trim() === "") {
    return { success: false, error: "Correction reason is mandatory for auditing purposes." }
  }

  try {
    // Transaction for safe editing
    return await db.transaction(async (tx) => {
      // 1. Fetch current entry
      const [entry] = await tx.select().from(journal_entries).where(eq(journal_entries.id, input.id))
      if (!entry) throw new Error("Journal entry not found")
      
      if (entry.auto_generated) {
        throw new Error("Cannot edit auto-generated journal entries directly. Please edit or void the originating source document.")
      }

      // 2. Fetch current lines
      const currentLines = await tx.select({
        id: journal_lines.id,
        account_id: journal_lines.account_id,
        account_code: accounts.code,
        debit: journal_lines.debit,
        credit: journal_lines.credit,
        description: journal_lines.description,
      })
      .from(journal_lines)
      .innerJoin(accounts, eq(accounts.id, journal_lines.account_id))
      .where(eq(journal_lines.journal_entry_id, input.id))

      // 3. Create snapshot
      const snapshot = {
        entry,
        lines: currentLines
      }

      // 4. Update Header
      await tx.update(journal_entries)
        .set({
          description: input.description,
          edited_at: new Date(),
          edited_by: session.user.id,
          edit_reason: input.editReason,
          original_data: snapshot,
        })
        .where(eq(journal_entries.id, input.id))

      // 5. Delete old lines
      await tx.delete(journal_lines).where(eq(journal_lines.journal_entry_id, input.id))

      // 6. Insert new lines
      const lineValues = await Promise.all(
        input.lines.map(async (line) => ({
          journal_entry_id: input.id,
          account_id: await getAccountId(line.accountCode, tx),
          debit: line.debit ? line.debit.toString() : '0',
          credit: line.credit ? line.credit.toString() : '0',
          description: line.description ?? null,
        }))
      )

      await tx.insert(journal_lines).values(lineValues)

      return { success: true }
    })
  } catch (err) {
    return { success: false, error: (err as Error).message }
  }
}

