"use client"

import { useState, useEffect, useTransition, useRef, useCallback } from 'react'
import { useReactToPrint } from 'react-to-print'
import { FinancePrintTemplate } from '@/components/finance/FinancePrintTemplate'
import ManualJournalDrawer from '@/components/accounting/ManualJournalDrawer'
import { useRouter, useSearchParams } from 'next/navigation'
import {
  Card, CardContent, CardHeader, CardTitle
} from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Table, TableBody, TableCell, TableHead,
  TableHeader, TableRow
} from '@/components/ui/table'
import {
  TrendingUp, TrendingDown, Scale, Receipt,
  BookOpen, LayoutDashboard, Plus, CheckCircle2,
  XCircle, Clock, ArrowUpRight, ArrowDownRight,
  Wallet, FileText, IndianRupee, Download, Printer,
  CalendarRange, ChevronRight, ChevronDown, Loader2,
  PenLine
} from 'lucide-react'
import {
  createExpenseRecord, approveExpense, rejectExpense,
  getJournalLines, getJournalEntries, exportJournalLedger,
  getActiveAccounts,
} from '@/actions/finance'
import { fmtINR } from '@/lib/utils'

// ── Types ───────────────────────────────────────────

type PLData = {
  revenue: Array<{ code: string; name: string; net: string }>
  expenses: Array<{ code: string; name: string; net: string }>
  totalRevenue: number
  totalExpenses: number
  netProfit: number
} | null

type BSData = {
  assets: Array<{ code: string; name: string; balance: string }>
  liabilities: Array<{ code: string; name: string; balance: string }>
  equity: Array<{ code: string; name: string; balance: string }>
  netProfit: number
} | null

type GSTData = {
  gst: Array<{
    code: string; name: string
    collected: string; paid: string
  }>
} | null

type JournalEntry = {
  id: string
  date: Date
  description: string
  referenceSource: string
  referenceId: string | null
  branchId: string
  branchName: string | null
  financialYear: string
  status: string
  autoGenerated: boolean | null
  amount: number
}

type MarginProduct = {
  product_id: string
  model_name: string
  brand: string
  product_code: string
  mrp: string | null
  units_sold: string
  total_revenue: string
  total_cogs: string
  gross_profit: string
  margin_pct: string
  total_discounts: string
  manager_approved_discounts: string
}

type MarginData = {
  products: MarginProduct[]
  summary: {
    totalRevenue: number
    totalCOGS: number
    grossProfit: number
    overallMarginPct: number
    totalDiscounts: number
    totalUnitsSold: number
  }
} | null

type Expense = {
  id: string
  branch_id: string
  created_by: string
  amount: string
  expense_account: string
  payment_account: string
  description: string
  receipt_url: string | null
  status: string
  approved_by: string | null
  approved_at: Date | null
  journal_entry_id: string | null
  created_at: Date | null
}

// ── Helper formatters ───────────────────────────────

function fmtDate(date: Date | string): string {
  return new Date(date).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
  })
}

function sourceColor(source: string): string {
  const map: Record<string, string> = {
    GRN:     'bg-blue-100 text-blue-800 border-blue-200',
    SALES:   'bg-green-100 text-green-800 border-green-200',
    EXPENSE: 'bg-orange-100 text-orange-800 border-orange-200',
    PAYMENT:     'bg-purple-100 text-purple-800 border-purple-200',
    SHORT_CLOSE: 'bg-orange-100 text-orange-800 border-orange-200',
    DEBIT_NOTE:  'bg-red-100 text-red-800 border-red-200',
    RETURN:      'bg-orange-100 text-orange-800 border-orange-200',
    MANUAL:      'bg-slate-100 text-slate-600 border-slate-200',
  }
  return map[source] ?? map['MANUAL']
}

function statusColor(status: string): string {
  const map: Record<string, string> = {
    pending:  'bg-yellow-100 text-yellow-800 border-yellow-200',
    approved: 'bg-green-100 text-green-800 border-green-200',
    rejected: 'bg-red-100 text-red-800 border-red-200',
    posted:   'bg-slate-100 text-slate-600 border-slate-200',
  }
  return map[status] ?? map['posted']
}

// ── EXPENSE ACCOUNTS for dropdown ──────────────────
const EXPENSE_ACCOUNTS = [
  { code: '5010', name: 'Cost of Goods Sold' },
  { code: '5020', name: 'Freight & Logistics' },
  { code: '5030', name: 'Utilities' },
  { code: '5040', name: 'Rent' },
  { code: '5050', name: 'Salaries & Wages' },
  { code: '5060', name: 'Marketing & Advertising' },
  { code: '5070', name: 'Miscellaneous Expense' },
]

// Payment accounts are fetched dynamically from the server
// to reflect branch-scoped cash accounts.
const STATIC_PAYMENT_FALLBACK = [
  { code: '1010', name: 'Cash & Petty Cash' },
  { code: '1020', name: 'Bank Accounts' },
]

// ── Main component ──────────────────────────────────

export default function AccountingClient({
  activeTab,
  isAdmin,
  pl,
  bs,
  gst,
  journal,
  expenses: initialExpenses,
  userId,
  branchId,
  fromDate,
  toDate,
  fyStart,
  fyEnd,
  marginData,
  branchList = [],
}: {
  activeTab: string
  isAdmin: boolean
  pl: PLData
  bs: BSData
  gst: GSTData
  journal: JournalEntry[]
  expenses: Expense[]
  userId: string
  branchId: string | null
  fromDate: string
  toDate: string
  fyStart: string
  fyEnd: string
  marginData: MarginData
  branchList?: { id: string; name: string }[]
}) {
  const router = useRouter()
  const [tab, setTab] = useState(activeTab)
  const [expenses, setExpenses] = useState(initialExpenses)
  const [dateFrom, setDateFrom] = useState(fromDate)
  const [dateTo, setDateTo] = useState(toDate)

  // ── Journal pagination state (B8) ──────────────────
  const [journalEntries, setJournalEntries] = useState<JournalEntry[]>(journal)
  const [journalCursor, setJournalCursor] = useState<{ lastDate: string; lastId: string } | undefined>(undefined)
  const [journalHasMore, setJournalHasMore] = useState(journal.length >= 50)
  const [loadingMore, setLoadingMore] = useState(false)
  const [manualJournalOpen, setManualJournalOpen] = useState(false)

  // Refresh journal after manual entry
  const handleJournalPosted = useCallback(() => {
    // Reset pagination and refresh from server
    router.refresh()
    setJournalCursor(undefined)
    setJournalHasMore(true)
  }, [router])

  async function loadMoreJournal() {
    // Determine cursor from last entry in current list
    const last = journalEntries[journalEntries.length - 1]
    if (!last) return

    const cursor = journalCursor ?? {
      lastDate: new Date(last.date).toISOString(),
      lastId: last.id,
    }

    setLoadingMore(true)
    try {
      const res = await getJournalEntries({
        branchId: branchId ?? undefined,
        fromDate: dateFrom,
        toDate: dateTo,
        cursor,
      })
      if (res.success) {
        setJournalEntries(prev => [...prev, ...res.entries])
        setJournalHasMore(res.hasMore ?? false)
        setJournalCursor(res.nextCursor)
      }
    } catch {
      // Silently fail — user can retry
    } finally {
      setLoadingMore(false)
    }
  }

  // ── Print ref & hook ────────────────────────────────
  const printRef = useRef<HTMLDivElement>(null)

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: `OPS360-Finance-${tab}-${dateFrom}-${dateTo}`,
    onBeforePrint: async () => {
      await new Promise(resolve => setTimeout(resolve, 300))
    },
    onAfterPrint: () => {
      // cleanup if needed
    },
  })

  const printReportType = (() => {
    if (tab === 'balance-sheet') return 'balance-sheet' as const
    if (tab === 'journal')       return 'journal'       as const
    if (tab === 'expenses')      return 'expenses'      as const
    if (tab === 'margins')       return 'margins'       as const
    return 'pl' as const // dashboard shows P&L
  })()

  // Dynamic payment accounts from server (branch-scoped)
  const [paymentAccounts, setPaymentAccounts] = useState(STATIC_PAYMENT_FALLBACK)

  useEffect(() => {
    getActiveAccounts().then(res => {
      if (res.success) {
        // Filter to only show asset-type accounts suitable as payment sources
        const cashAndBank = res.accounts.filter(
          (a: { code: string; type: string }) =>
            a.code.startsWith('1010') || a.code === '1020'
        )
        if (cashAndBank.length > 0) {
          setPaymentAccounts(cashAndBank.map((a: { code: string; name: string }) => ({
            code: a.code,
            name: a.name,
          })))
        }
      }
    })
  }, [])

  // Expense form state
  const [showExpenseForm, setShowExpenseForm] = useState(false)
  const [expAmount, setExpAmount] = useState('')
  const [expAccount, setExpAccount] = useState('5070')
  const [expPayment, setExpPayment] = useState('')  // set dynamically below
  const [expDesc, setExpDesc] = useState('')
  const [expError, setExpError] = useState('')
  const [isPending, startTransition] = useTransition()

  // Set default payment account once dynamic accounts load
  useEffect(() => {
    if (paymentAccounts.length > 0 && !expPayment) {
      // Prefer the first cash account (1010-XX or 1010)
      const firstCash = paymentAccounts.find(a => a.code.startsWith('1010'))
      setExpPayment(firstCash?.code ?? paymentAccounts[0].code)
    }
  }, [paymentAccounts, expPayment])

  function switchTab(t: string) {
    setTab(t)
    router.push(
      `/accounting?tab=${t}&fromDate=${dateFrom}&toDate=${dateTo}`,
      { scroll: false }
    )
  }

  // ── Export CSV ────────────────────────────────────
  function handleExportCSV() {
    const rows: string[][] = []
    const period = `${dateFrom} to ${dateTo}`

    if (tab === 'dashboard' || tab === 'balance-sheet') {
      rows.push(['PROFIT & LOSS STATEMENT'])
      rows.push([`Period: ${period}`])
      rows.push([])
      rows.push(['REVENUE'])
      rows.push(['Account Code', 'Account Name', 'Amount'])
      ;(pl?.revenue ?? []).forEach(r =>
        rows.push([r.code, r.name, Number(r.net).toFixed(2)])
      )
      rows.push(['', 'Total Revenue',
        (pl?.totalRevenue ?? 0).toFixed(2)])
      rows.push([])
      rows.push(['EXPENSES'])
      rows.push(['Account Code', 'Account Name', 'Amount'])
      ;(pl?.expenses ?? []).forEach(e =>
        rows.push([e.code, e.name,
          Math.abs(Number(e.net)).toFixed(2)])
      )
      rows.push(['', 'Total Expenses',
        (pl?.totalExpenses ?? 0).toFixed(2)])
      rows.push([])
      rows.push(['', 'NET PROFIT / LOSS',
        (pl?.netProfit ?? 0).toFixed(2)])
    }

    if (tab === 'journal') {
      // B11: Fetch audit-ready line-level data from the server
      // instead of dumping the summary-level UI data.
      exportJournalLedger({
        branchId: branchId ?? undefined,
        fromDate: dateFrom,
        toDate: dateTo,
      }).then(res => {
        if (!res.success || !res.lines) {
          alert('Export failed: ' + (res.error ?? 'Unknown error'))
          return
        }
        const csvRows: string[][] = []
        csvRows.push(['JOURNAL LEDGER — DETAILED EXPORT'])
        csvRows.push([`Period: ${period}`])
        csvRows.push([])
        csvRows.push([
          'Entry Date', 'Source', 'Reference', 'Entry Description',
          'Branch', 'Account Code', 'Account Name',
          'Line Description', 'Debit', 'Credit',
        ])
        res.lines.forEach(l => csvRows.push([
          new Date(l.entryDate).toLocaleDateString('en-IN'),
          l.source,
          l.referenceId,
          l.entryDescription,
          l.branchName,
          l.accountCode,
          l.accountName,
          l.lineDescription,
          l.debit > 0 ? l.debit.toFixed(2) : '',
          l.credit > 0 ? l.credit.toFixed(2) : '',
        ]))
        // Trigger download
        const csvContent = csvRows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n')
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `journal_ledger_${dateFrom}_${dateTo}.csv`
        a.click()
        URL.revokeObjectURL(url)
      })
      return // early return — the async export handles its own download
    }

    if (tab === 'expenses') {
      rows.push(['EXPENSE RECORDS'])
      rows.push([`Period: ${period}`])
      rows.push([])
      rows.push(['Date', 'Description', 'Category',
        'Payment Source', 'Amount', 'Status'])
      expenses.forEach(e => rows.push([
        e.created_at ? new Date(e.created_at).toLocaleDateString('en-IN') : '',
        e.description,
        EXPENSE_ACCOUNTS.find(
          a => a.code === e.expense_account
        )?.name ?? e.expense_account,
        paymentAccounts.find(
          a => a.code === e.payment_account
        )?.name ?? e.payment_account,
        Number(e.amount).toFixed(2),
        e.status,
      ]))
    }

    if (tab === 'margins') {
      rows.push(['PRODUCT MARGIN ANALYSIS'])
      rows.push([`Period: ${period}`])
      rows.push([])
      rows.push([
        'Product Code', 'Product Name', 'Brand', 'MRP',
        'Units Sold', 'Revenue', 'COGS', 'Gross Profit',
        'Margin %', 'Discounts', 'Manager Approvals'
      ])
      ;(marginData?.products ?? []).forEach(p =>
        rows.push([
          p.product_code,
          p.model_name,
          p.brand,
          p.mrp ?? '',
          Number(p.units_sold).toString(),
          Number(p.total_revenue).toFixed(2),
          Number(p.total_cogs).toFixed(2),
          Number(p.gross_profit).toFixed(2),
          Number(p.margin_pct).toFixed(1) + '%',
          Number(p.total_discounts).toFixed(2),
          Number(p.manager_approved_discounts).toString(),
        ])
      )
      rows.push([])
      rows.push([
        '', 'TOTALS', '', '',
        String(marginData?.summary.totalUnitsSold ?? 0),
        (marginData?.summary.totalRevenue ?? 0).toFixed(2),
        (marginData?.summary.totalCOGS ?? 0).toFixed(2),
        (marginData?.summary.grossProfit ?? 0).toFixed(2),
        (marginData?.summary.overallMarginPct ?? 0).toFixed(1) + '%',
        (marginData?.summary.totalDiscounts ?? 0).toFixed(2),
        '',
      ])
    }

    if (gst && gst.gst.length > 0) {
      rows.push([])
      rows.push(['GST SUMMARY'])
      rows.push(['Account Code', 'Account Name',
        'Collected (Output)', 'Paid/ITC (Input)',
        'Net Payable'])
      gst.gst.forEach(g => rows.push([
        g.code,
        g.name,
        Number(g.collected).toFixed(2),
        Number(g.paid).toFixed(2),
        (Number(g.collected) - Number(g.paid)).toFixed(2),
      ]))
    }

    const csv = rows
      .map(row =>
        row.map(cell =>
          `"${String(cell).replace(/"/g, '""')}"`
        ).join(',')
      )
      .join('\n')

    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `ops360-finance-${tab}-${dateFrom}-${dateTo}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── Export PDF (react-to-print) ────────────────────────
  function handleExportPDF() {
    handlePrint()
  }

  // ── Submit expense ────────────────────────────────
  async function handleSubmitExpense() {
    setExpError('')
    if (!expAmount || Number(expAmount) <= 0) {
      setExpError('Enter a valid amount')
      return
    }
    if (!expDesc.trim()) {
      setExpError('Description is required')
      return
    }
    startTransition(async () => {
      const result = await createExpenseRecord({
        amount: Number(expAmount),
        expenseAccount: expAccount,
        paymentAccount: expPayment,
        description: expDesc.trim(),
      })
      if (result.success) {
        setExpenses(prev => [result.record as any, ...prev])
        setShowExpenseForm(false)
        setExpAmount('')
        setExpDesc('')
      } else {
        setExpError(result.error ?? 'Failed to submit')
      }
    })
  }

  // ── Approve / Reject expense ──────────────────────
  async function handleApprove(id: string) {
    startTransition(async () => {
      const result = await approveExpense({ expenseId: id })
      if (result.success) {
        setExpenses(prev => prev.map(e =>
          e.id === id ? { ...e, status: 'approved' } : e
        ))
      }
    })
  }

  async function handleReject(id: string) {
    startTransition(async () => {
      const result = await rejectExpense({ expenseId: id })
      if (result.success) {
        setExpenses(prev => prev.map(e =>
          e.id === id ? { ...e, status: 'rejected' } : e
        ))
      }
    })
  }

  // ── Tab definitions ───────────────────────────────
  const tabs = [
    { id: 'dashboard', label: 'Dashboard',
      icon: LayoutDashboard },
    { id: 'balance-sheet', label: 'Balance Sheet',
      icon: Scale },
    { id: 'journal',   label: 'Journal Ledger',
      icon: BookOpen },
    { id: 'expenses',  label: 'Expenses',
      icon: Receipt },
    { id: 'margins',   label: 'Margin Report',
      icon: TrendingUp },
  ]

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">

      {/* ── Page header ── */}
      <div className="flex items-center justify-between no-print">
        <div>
          <h1 className="text-2xl font-bold tracking-tight
            flex items-center gap-2">
            <Wallet className="h-6 w-6 text-indigo-600" />
            Finance & Accounts
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Automated double-entry accounting •
            {isAdmin ? ' All Branches' : ' Your Branch'}
          </p>
        </div>
      </div>

      {/* ── Tab bar ── */}
      <div className="flex gap-1 border-b no-print">
        {tabs.map(t => (
          <button
            key={t.id}
            onClick={() => switchTab(t.id)}
            className={`flex items-center gap-2 px-4 py-2.5
              text-sm font-medium border-b-2 transition-colors
              ${tab === t.id
                ? 'border-indigo-600 text-indigo-600'
                : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
          >
            <t.icon className="h-4 w-4" />
            {t.label}
          </button>
        ))}
      </div>

      {/* ── Date range + Export controls ── */}
      <div className="flex flex-wrap items-center gap-3
        p-4 bg-slate-50 rounded-xl border border-slate-200
        no-print">

        {/* Quick FY reset */}
        <button
          onClick={() => {
            setDateFrom(fyStart)
            setDateTo(fyEnd)
            router.push(
              `/accounting?tab=${tab}&fromDate=${fyStart}&toDate=${fyEnd}`,
              { scroll: false }
            )
          }}
          className="flex items-center gap-1.5 text-xs font-semibold
            px-3 py-1.5 rounded-lg bg-indigo-100 text-indigo-700
            hover:bg-indigo-200 transition-colors"
        >
          <CalendarRange className="h-3.5 w-3.5" />
          Current FY
        </button>

        <div className="flex items-center gap-2">
          <label className="text-xs font-semibold uppercase
            tracking-widest text-slate-500">
            From
          </label>
          <input
            type="date"
            value={dateFrom}
            onChange={e => setDateFrom(e.target.value)}
            className="text-sm border border-slate-200 rounded-lg
              px-2 py-1 focus:outline-none focus:ring-1
              focus:ring-indigo-500 bg-white"
          />
        </div>

        <div className="flex items-center gap-2">
          <label className="text-xs font-semibold uppercase
            tracking-widest text-slate-500">
            To
          </label>
          <input
            type="date"
            value={dateTo}
            onChange={e => setDateTo(e.target.value)}
            className="text-sm border border-slate-200 rounded-lg
              px-2 py-1 focus:outline-none focus:ring-1
              focus:ring-indigo-500 bg-white"
          />
        </div>

        <button
          onClick={() => {
            router.push(
              `/accounting?tab=${tab}&fromDate=${dateFrom}&toDate=${dateTo}`,
              { scroll: false }
            )
          }}
          className="text-xs font-semibold px-3 py-1.5
            rounded-lg bg-slate-800 text-white
            hover:bg-slate-700 transition-colors"
        >
          Apply
        </button>

        {/* Export buttons — right aligned */}
        <div className="ml-auto flex items-center gap-2">
          <button
            onClick={() => handleExportCSV()}
            className="flex items-center gap-1.5 text-xs
              font-semibold px-3 py-1.5 rounded-lg
              border border-slate-300 text-slate-700
              hover:bg-slate-100 transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            Export CSV
          </button>
          <button
            onClick={() => handleExportPDF()}
            className="flex items-center gap-1.5 text-xs
              font-semibold px-3 py-1.5 rounded-lg
              bg-slate-800 text-white
              hover:bg-slate-700 transition-colors"
          >
            <Printer className="h-3.5 w-3.5" />
            Print / PDF
          </button>
        </div>
      </div>

      {/* ── Printable content wrapper ── */}
      <div className="finance-printable">

        {/* Print-only header */}
        <div className="hidden print:block mb-6 border-b pb-4">
          <h1 className="text-xl font-bold text-slate-900">
            Ethan Home Appliances — OPS360 ERP
          </h1>
          <p className="text-sm text-slate-600 mt-1">
            {tab === 'dashboard' && 'Profit & Loss Statement'}
            {tab === 'balance-sheet' && 'Balance Sheet'}
            {tab === 'journal' && 'Journal Ledger'}
            {tab === 'expenses' && 'Expense Report'}
          </p>
          <p className="text-xs text-slate-500 mt-0.5">
            Period: {dateFrom} to {dateTo}
          </p>
          <p className="text-xs text-slate-400" suppressHydrationWarning>
            Generated: {new Date().toLocaleString('en-IN')}
          </p>
        </div>

      {/* ══════════════════════════════════════════
          TAB: DASHBOARD
      ══════════════════════════════════════════ */}
      {tab === 'dashboard' && (
        <div className="space-y-6">

          {/* P&L summary cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card className="border-green-200 bg-green-50/30">
              <CardContent className="pt-6">
                <div className="flex items-center
                  justify-between">
                  <div>
                    <p className="text-xs font-semibold
                      uppercase tracking-widest
                      text-green-700">
                      Total Revenue
                    </p>
                    <p className="text-2xl font-bold
                      text-green-800 mt-1">
                      {fmtINR(pl?.totalRevenue ?? 0)}
                    </p>
                    <p className="text-xs text-green-600 mt-1">
                      Current financial year
                    </p>
                  </div>
                  <div className="p-3 bg-green-100
                    rounded-full">
                    <TrendingUp className="h-5 w-5
                      text-green-600" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-red-200 bg-red-50/30">
              <CardContent className="pt-6">
                <div className="flex items-center
                  justify-between">
                  <div>
                    <p className="text-xs font-semibold
                      uppercase tracking-widest text-red-700">
                      Total Expenses
                    </p>
                    <p className="text-2xl font-bold
                      text-red-800 mt-1">
                      {fmtINR(Math.abs(pl?.totalExpenses ?? 0))}
                    </p>
                    <p className="text-xs text-red-600 mt-1">
                      Current financial year
                    </p>
                  </div>
                  <div className="p-3 bg-red-100 rounded-full">
                    <TrendingDown className="h-5 w-5
                      text-red-600" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className={`border-2 ${
              (pl?.netProfit ?? 0) >= 0
                ? 'border-indigo-200 bg-indigo-50/30'
                : 'border-orange-200 bg-orange-50/30'
            }`}>
              <CardContent className="pt-6">
                <div className="flex items-center
                  justify-between">
                  <div>
                    <p className="text-xs font-semibold
                      uppercase tracking-widest
                      text-indigo-700">
                      Net Profit / Loss
                    </p>
                    <p className={`text-2xl font-bold mt-1
                      ${(pl?.netProfit ?? 0) >= 0
                        ? 'text-indigo-800'
                        : 'text-orange-700'
                      }`}>
                      {fmtINR(pl?.netProfit ?? 0)}
                    </p>
                    <p className="text-xs text-muted-foreground mt-1">
                      {(pl?.netProfit ?? 0) >= 0
                        ? '▲ Profitable'
                        : '▼ Net loss'}
                    </p>
                  </div>
                  <div className={`p-3 rounded-full ${
                    (pl?.netProfit ?? 0) >= 0
                      ? 'bg-indigo-100'
                      : 'bg-orange-100'
                  }`}>
                    <Scale className={`h-5 w-5 ${
                      (pl?.netProfit ?? 0) >= 0
                        ? 'text-indigo-600'
                        : 'text-orange-600'
                    }`} />
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* GST Summary */}
          {gst && gst.gst.length > 0 && (
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-slate-500">
                  GST Position — Current FY
                </CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Account</TableHead>
                      <TableHead className="text-right">
                        Collected (Output)
                      </TableHead>
                      <TableHead className="text-right">
                        Paid / ITC (Input)
                      </TableHead>
                      <TableHead className="text-right">
                        Net Payable
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {gst.gst.map(row => (
                      <TableRow key={row.code}>
                        <TableCell className="font-medium">
                          <span className="text-xs text-muted-foreground mr-2">
                            {row.code}
                          </span>
                          {row.name}
                        </TableCell>
                        <TableCell className="text-right text-green-700">
                          {fmtINR(Number(row.collected))}
                        </TableCell>
                        <TableCell className="text-right text-blue-700">
                          {fmtINR(Number(row.paid))}
                        </TableCell>
                        <TableCell className={`text-right font-semibold ${
                          Number(row.collected) - Number(row.paid) > 0
                            ? 'text-red-700'
                            : 'text-green-700'
                        }`}>
                          {fmtINR(
                            Number(row.collected) - Number(row.paid)
                          )}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}

          {/* P&L breakdown */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

            {/* Revenue breakdown */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-green-600">
                  Revenue Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent>
                {pl?.revenue.length ? (
                  <div className="space-y-2">
                    {pl.revenue.map(r => (
                      <div key={r.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {r.code}
                          </span>
                          {r.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-green-700">
                          {fmtINR(Number(r.net))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-green-200">
                      <span className="text-sm font-bold">
                        Total Revenue
                      </span>
                      <span className="text-sm font-bold
                        text-green-700">
                        {fmtINR(pl.totalRevenue)}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">
                    No revenue recorded yet
                  </p>
                )}
              </CardContent>
            </Card>

            {/* Expense breakdown */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-red-600">
                  Expense Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent>
                {pl?.expenses.length ? (
                  <div className="space-y-2">
                    {pl.expenses.map(e => (
                      <div key={e.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {e.code}
                          </span>
                          {e.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-red-700">
                          {fmtINR(Math.abs(Number(e.net)))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-red-200">
                      <span className="text-sm font-bold">
                        Total Expenses
                      </span>
                      <span className="text-sm font-bold
                        text-red-700">
                        {fmtINR(Math.abs(pl.totalExpenses))}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">
                    No expenses recorded yet
                  </p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Recent journal entries */}
          <Card>
            <CardHeader className="pb-3 flex flex-row
              items-center justify-between">
              <CardTitle className="text-sm font-semibold
                uppercase tracking-widest text-slate-500">
                Recent Journal Entries
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => switchTab('journal')}
                className="text-xs text-indigo-600
                  hover:text-indigo-700"
              >
                View All →
              </Button>
            </CardHeader>
            <CardContent>
              {journal.length > 0 ? (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead>Source</TableHead>
                      <TableHead>Branch</TableHead>
                      <TableHead>FY</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {journal.slice(0, 10).map(entry => (
                      <TableRow key={entry.id}>
                        <TableCell className="text-xs
                          text-muted-foreground whitespace-nowrap">
                          {fmtDate(entry.date)}
                        </TableCell>
                        <TableCell className="text-sm
                          max-w-xs truncate">
                          {entry.description}
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline"
                            className={`text-xs ${
                              sourceColor(entry.referenceSource)
                            }`}>
                            {entry.referenceSource}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-xs
                          text-muted-foreground">
                          {entry.branchName ?? '—'}
                        </TableCell>
                        <TableCell className="text-xs
                          text-muted-foreground">
                          {entry.financialYear}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              ) : (
                <p className="text-sm text-muted-foreground
                  text-center py-8">
                  No journal entries yet. They will appear
                  automatically after GRN receipts and
                  POS sales.
                </p>
              )}
            </CardContent>
          </Card>
        </div>
      )}

      {/* ══════════════════════════════════════════
          TAB: BALANCE SHEET
      ══════════════════════════════════════════ */}
      {tab === 'balance-sheet' && (
        <div className="space-y-4">

          {/* Accounting equation banner */}
          <Card className="bg-slate-900 text-white border-0">
            <CardContent className="pt-6">
              <div className="flex items-center
                justify-between text-center">
                <div>
                  <p className="text-xs uppercase tracking-widest
                    text-slate-400 mb-1">Total Assets</p>
                  <p className="text-2xl font-bold text-white">
                    {fmtINR(
                      (bs?.assets ?? []).reduce(
                        (s, a) => s + Number(a.balance), 0
                      )
                    )}
                  </p>
                </div>
                <div className="text-2xl font-light
                  text-slate-400">=</div>
                <div>
                  <p className="text-xs uppercase tracking-widest
                    text-slate-400 mb-1">Total Liabilities</p>
                  <p className="text-2xl font-bold
                    text-red-400">
                    {fmtINR(Math.abs(
                      (bs?.liabilities ?? []).reduce(
                        (s, l) => s + Number(l.balance), 0
                      )
                    ))}
                  </p>
                </div>
                <div className="text-2xl font-light
                  text-slate-400">+</div>
                <div>
                  <p className="text-xs uppercase tracking-widest
                    text-slate-400 mb-1">Total Equity</p>
                  <p className="text-2xl font-bold
                    text-green-400">
                    {fmtINR(Math.abs(
                      (bs?.equity ?? []).reduce(
                        (s, e) => s + Number(e.balance), 0
                      )
                    ))}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Three columns: Assets | Liabilities | Equity */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

            {/* Assets */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-blue-600">
                  Assets
                </CardTitle>
              </CardHeader>
              <CardContent>
                {(bs?.assets ?? []).length > 0 ? (
                  <div className="space-y-2">
                    {(bs?.assets ?? []).map(a => (
                      <div key={a.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {a.code}
                          </span>
                          {a.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-blue-700">
                          {fmtINR(Number(a.balance))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-blue-200">
                      <span className="text-sm font-bold">
                        Total
                      </span>
                      <span className="text-sm font-bold
                        text-blue-700">
                        {fmtINR(
                          (bs?.assets ?? []).reduce(
                            (s, a) => s + Number(a.balance), 0
                          )
                        )}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">No asset entries</p>
                )}
              </CardContent>
            </Card>

            {/* Liabilities */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-red-600">
                  Liabilities
                </CardTitle>
              </CardHeader>
              <CardContent>
                {(bs?.liabilities ?? []).length > 0 ? (
                  <div className="space-y-2">
                    {(bs?.liabilities ?? []).map(l => (
                      <div key={l.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {l.code}
                          </span>
                          {l.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-red-700">
                          {fmtINR(Math.abs(Number(l.balance)))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-red-200">
                      <span className="text-sm font-bold">
                        Total
                      </span>
                      <span className="text-sm font-bold
                        text-red-700">
                        {fmtINR(Math.abs(
                          (bs?.liabilities ?? []).reduce(
                            (s, l) => s + Number(l.balance), 0
                          )
                        ))}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">No liability entries</p>
                )}
              </CardContent>
            </Card>

            {/* Equity */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-green-600">
                  Equity
                </CardTitle>
              </CardHeader>
              <CardContent>
                {(bs?.equity ?? []).length > 0 ? (
                  <div className="space-y-2">
                    {(bs?.equity ?? []).map(e => (
                      <div key={e.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {e.code}
                          </span>
                          {e.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-green-700">
                          {fmtINR(Math.abs(Number(e.balance)))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-green-200">
                      <span className="text-sm font-bold">
                        Total
                      </span>
                      <span className="text-sm font-bold
                        text-green-700">
                        {fmtINR(Math.abs(
                          (bs?.equity ?? []).reduce(
                            (s, e) => s + Number(e.balance), 0
                          )
                        ))}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">No equity entries</p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Balance check */}
          {bs && (() => {
            const totalAssets = bs.assets.reduce(
              (s, a) => s + Number(a.balance), 0)
            // Liabilities and Equity are credit-natural (negative in DR-CR),
            // so we use Math.abs for the equation check: A = |L| + |E|
            const totalLiabEquity =
              Math.abs(bs.liabilities.reduce(
                (s, l) => s + Number(l.balance), 0)) +
              Math.abs(bs.equity.reduce(
                (s, e) => s + Number(e.balance), 0))
            const diff = Math.abs(totalAssets - totalLiabEquity)
            return diff > 1 ? (
              <Card className="border-orange-200 bg-orange-50">
                <CardContent className="pt-4 pb-4">
                  <p className="text-sm text-orange-700
                    text-center">
                    ⚠️ Balance sheet is out of balance by
                    {' '}{fmtINR(diff)}. This may indicate
                    missing opening balance entries.
                  </p>
                </CardContent>
              </Card>
            ) : (
              <Card className="border-green-200 bg-green-50">
                <CardContent className="pt-4 pb-4">
                  <p className="text-sm text-green-700
                    text-center flex items-center
                    justify-center gap-2">
                    <CheckCircle2 className="h-4 w-4" />
                    Balance sheet is balanced ✓
                  </p>
                </CardContent>
              </Card>
            )
          })()}
        </div>
      )}

      {/* ══════════════════════════════════════════
          TAB: JOURNAL LEDGER
      ══════════════════════════════════════════ */}
      {tab === 'journal' && (
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="h-4 w-4 text-indigo-600" />
                Journal Ledger
              </CardTitle>
              {isAdmin && (
                <Button
                  size="sm"
                  onClick={() => setManualJournalOpen(true)}
                  className="bg-indigo-600 hover:bg-indigo-700 text-white
                    text-xs font-semibold gap-1.5 h-8 px-3"
                >
                  <PenLine className="h-3.5 w-3.5" />
                  Post Manual Journal
                </Button>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {journalEntries.length > 0 ? (
              <>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-8"></TableHead>
                      <TableHead>Date</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead>Source</TableHead>
                      <TableHead>Branch</TableHead>
                      <TableHead>FY</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead className="text-right">Total Amount</TableHead>
                      <TableHead>Status</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {journalEntries.map(entry => (
                      <JournalEntryRow
                        key={entry.id}
                        entry={entry}
                      />
                    ))}
                  </TableBody>
                </Table>

                {/* B8: Load More button */}
                {journalHasMore && (
                  <div className="flex justify-center pt-4">
                    <Button
                      variant="outline"
                      onClick={loadMoreJournal}
                      disabled={loadingMore}
                      className="gap-2"
                    >
                      {loadingMore ? (
                        <><Loader2 className="h-4 w-4 animate-spin" /> Loading…</>
                      ) : (
                        'Load More Entries'
                      )}
                    </Button>
                  </div>
                )}

                {!journalHasMore && journalEntries.length > 0 && (
                  <p className="text-center text-xs text-muted-foreground pt-4">
                    Showing all {journalEntries.length} entries
                  </p>
                )}
              </>
            ) : (
              <p className="text-sm text-muted-foreground
                text-center py-12">
                No journal entries yet. GRN receipts and
                POS sales automatically create entries here.
              </p>
            )}
          </CardContent>
        </Card>
      )}

      {/* ══════════════════════════════════════════
          TAB: EXPENSES
      ══════════════════════════════════════════ */}
      {tab === 'expenses' && (
        <div className="space-y-4">

          {/* Submit expense button + form */}
          <div className="flex justify-end">
            <Button
              onClick={() => setShowExpenseForm(!showExpenseForm)}
              className="gap-2 bg-[#001529] hover:bg-[#002a52]
                text-white"
            >
              <Plus className="h-4 w-4" />
              Submit Expense
            </Button>
          </div>

          {showExpenseForm && (
            <Card className="border-indigo-200">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm">
                  New Expense Record
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-semibold
                      uppercase tracking-widest text-slate-500">
                      Amount (₹)
                    </Label>
                    <Input
                      type="number"
                      placeholder="0.00"
                      value={expAmount}
                      onChange={e => setExpAmount(e.target.value)}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-semibold
                      uppercase tracking-widest text-slate-500">
                      Expense Category
                    </Label>
                    <select
                      value={expAccount}
                      onChange={e => setExpAccount(e.target.value)}
                      className="w-full text-sm border rounded-md
                        px-3 py-2 bg-white focus:outline-none
                        focus:ring-1 focus:ring-indigo-500"
                    >
                      {EXPENSE_ACCOUNTS.map(a => (
                        <option key={a.code} value={a.code}>
                          {a.name}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-semibold
                    uppercase tracking-widest text-slate-500">
                    Payment Source
                  </Label>
                  <select
                    value={expPayment}
                    onChange={e => setExpPayment(e.target.value)}
                    className="w-full text-sm border rounded-md
                      px-3 py-2 bg-white focus:outline-none
                      focus:ring-1 focus:ring-indigo-500"
                  >
                    {paymentAccounts.map(a => (
                      <option key={a.code} value={a.code}>
                        {a.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-semibold
                    uppercase tracking-widest text-slate-500">
                    Description
                  </Label>
                  <Textarea
                    placeholder="Brief description of the expense..."
                    value={expDesc}
                    onChange={e => setExpDesc(e.target.value)}
                    className="min-h-[80px]"
                  />
                </div>

                {expError && (
                  <p className="text-sm text-red-600">
                    {expError}
                  </p>
                )}

                <div className="flex gap-2 justify-end">
                  <Button
                    variant="outline"
                    onClick={() => setShowExpenseForm(false)}
                  >
                    Cancel
                  </Button>
                  <Button
                    onClick={handleSubmitExpense}
                    disabled={isPending}
                    className="bg-[#001529] hover:bg-[#002a52]
                      text-white"
                  >
                    {isPending ? 'Submitting...' : 'Submit'}
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Expense list */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2">
                <Receipt className="h-4 w-4 text-orange-500" />
                Expense Records
              </CardTitle>
            </CardHeader>
            <CardContent>
              {expenses.length > 0 ? (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead>Category</TableHead>
                      <TableHead>Payment</TableHead>
                      <TableHead className="text-right">
                        Amount
                      </TableHead>
                      <TableHead>Status</TableHead>
                      {isAdmin && (
                        <TableHead>Actions</TableHead>
                      )}
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {expenses.map(exp => (
                      <TableRow key={exp.id}>
                        <TableCell className="text-xs
                          text-muted-foreground whitespace-nowrap">
                          {exp.created_at ? fmtDate(exp.created_at) : '—'}
                        </TableCell>
                        <TableCell className="text-sm
                          max-w-xs truncate">
                          {exp.description}
                        </TableCell>
                        <TableCell className="text-xs">
                          {EXPENSE_ACCOUNTS.find(
                            a => a.code === exp.expense_account
                          )?.name ?? exp.expense_account}
                        </TableCell>
                        <TableCell className="text-xs">
                          {PAYMENT_ACCOUNTS.find(
                            a => a.code === exp.payment_account
                          )?.name ?? exp.payment_account}
                        </TableCell>
                        <TableCell className="text-right
                          font-semibold">
                          {fmtINR(Number(exp.amount))}
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline"
                            className={`text-xs ${
                              statusColor(exp.status)
                            }`}>
                            {exp.status === 'pending' && (
                              <Clock className="h-3 w-3 mr-1" />
                            )}
                            {exp.status === 'approved' && (
                              <CheckCircle2 className="h-3 w-3 mr-1" />
                            )}
                            {exp.status === 'rejected' && (
                              <XCircle className="h-3 w-3 mr-1" />
                            )}
                            {exp.status.charAt(0).toUpperCase()
                             + exp.status.slice(1)}
                          </Badge>
                        </TableCell>
                        {isAdmin && (
                          <TableCell>
                            {exp.status === 'pending' && (
                              <div className="flex gap-1">
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-7 text-xs
                                    text-green-700
                                    border-green-200
                                    hover:bg-green-50"
                                  onClick={() =>
                                    handleApprove(exp.id)}
                                  disabled={isPending}
                                >
                                  Approve
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-7 text-xs
                                    text-red-700
                                    border-red-200
                                    hover:bg-red-50"
                                  onClick={() =>
                                    handleReject(exp.id)}
                                  disabled={isPending}
                                >
                                  Reject
                                </Button>
                              </div>
                            )}
                          </TableCell>
                        )}
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              ) : (
                <p className="text-sm text-muted-foreground
                  text-center py-12">
                  No expenses recorded. Click Submit Expense
                  to add one.
                </p>
              )}
            </CardContent>
          </Card>
        </div>
      )}

      {/* ══════════════════════════════════════════
          TAB: MARGIN REPORT
      ══════════════════════════════════════════ */}
      {tab === 'margins' && (
        <div className="space-y-6">

          {/* Summary cards */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <Card className="border-blue-200 bg-blue-50/30">
              <CardContent className="pt-5 pb-4">
                <p className="text-[10px] font-semibold uppercase tracking-widest text-blue-600 mb-1">Total Revenue</p>
                <p className="text-xl font-bold text-blue-800">{fmtINR(marginData?.summary.totalRevenue ?? 0)}</p>
                <p className="text-xs text-blue-500 mt-1">{marginData?.summary.totalUnitsSold ?? 0} units sold</p>
              </CardContent>
            </Card>
            <Card className="border-orange-200 bg-orange-50/30">
              <CardContent className="pt-5 pb-4">
                <p className="text-[10px] font-semibold uppercase tracking-widest text-orange-600 mb-1">Cost of Goods Sold</p>
                <p className="text-xl font-bold text-orange-800">{fmtINR(marginData?.summary.totalCOGS ?? 0)}</p>
                <p className="text-xs text-orange-500 mt-1">Purchase + landed costs</p>
              </CardContent>
            </Card>
            <Card className={`border-2 ${(marginData?.summary.grossProfit ?? 0) >= 0 ? 'border-green-200 bg-green-50/30' : 'border-red-200 bg-red-50/30'}`}>
              <CardContent className="pt-5 pb-4">
                <p className="text-[10px] font-semibold uppercase tracking-widest text-green-600 mb-1">Gross Profit</p>
                <p className={`text-xl font-bold ${(marginData?.summary.grossProfit ?? 0) >= 0 ? 'text-green-800' : 'text-red-800'}`}>{fmtINR(marginData?.summary.grossProfit ?? 0)}</p>
                <p className="text-xs text-green-500 mt-1">Revenue − COGS</p>
              </CardContent>
            </Card>
            <Card className="border-indigo-200 bg-indigo-50/30">
              <CardContent className="pt-5 pb-4">
                <p className="text-[10px] font-semibold uppercase tracking-widest text-indigo-600 mb-1">Overall Margin</p>
                <p className="text-xl font-bold text-indigo-800">{(marginData?.summary.overallMarginPct ?? 0).toFixed(1)}%</p>
                <p className="text-xs text-indigo-500 mt-1">{fmtINR(marginData?.summary.totalDiscounts ?? 0)} in discounts applied</p>
              </CardContent>
            </Card>
          </div>

          {/* Margin health indicator */}
          {marginData && marginData.summary.overallMarginPct > 0 && (
            <Card className={`border-2 ${marginData.summary.overallMarginPct >= 20 ? 'border-green-200 bg-green-50' : marginData.summary.overallMarginPct >= 10 ? 'border-yellow-200 bg-yellow-50' : 'border-red-200 bg-red-50'}`}>
              <CardContent className="pt-4 pb-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className={`h-3 w-3 rounded-full ${marginData.summary.overallMarginPct >= 20 ? 'bg-green-500' : marginData.summary.overallMarginPct >= 10 ? 'bg-yellow-500' : 'bg-red-500'}`} />
                    <span className="text-sm font-semibold">
                      Margin Health:{' '}
                      {marginData.summary.overallMarginPct >= 20 ? 'Healthy' : marginData.summary.overallMarginPct >= 10 ? 'Moderate' : 'Critical — Below 10%'}
                    </span>
                  </div>
                  <span className="text-xs text-muted-foreground">Industry benchmark: 15-25% for appliance retail</span>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Product-level margin table */}
          <Card>
            <CardHeader className="pb-3 flex flex-row items-center justify-between">
              <CardTitle className="flex items-center gap-2 text-sm font-semibold uppercase tracking-widest text-slate-500">
                <TrendingUp className="h-4 w-4 text-indigo-600" />
                Product Margin Analysis
              </CardTitle>
              <span className="text-xs text-muted-foreground">{marginData?.products.length ?? 0} products with sales</span>
            </CardHeader>
            <CardContent>
              {(marginData?.products ?? []).length > 0 ? (
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow className="bg-slate-50">
                        <TableHead className="text-xs font-semibold">Product</TableHead>
                        <TableHead className="text-xs font-semibold text-right">MRP</TableHead>
                        <TableHead className="text-xs font-semibold text-right">Units Sold</TableHead>
                        <TableHead className="text-xs font-semibold text-right">Revenue</TableHead>
                        <TableHead className="text-xs font-semibold text-right">COGS</TableHead>
                        <TableHead className="text-xs font-semibold text-right">Gross Profit</TableHead>
                        <TableHead className="text-xs font-semibold text-right">Margin %</TableHead>
                        <TableHead className="text-xs font-semibold text-right">Discounts</TableHead>
                        <TableHead className="text-xs font-semibold text-center">Mgr Approvals</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {(marginData?.products ?? []).map(p => {
                        const marginPct = Number(p.margin_pct ?? 0)
                        const grossProfit = Number(p.gross_profit ?? 0)
                        const mgrApprovals = Number(p.manager_approved_discounts ?? 0)
                        return (
                          <TableRow key={p.product_id}>
                            <TableCell>
                              <div>
                                <p className="text-sm font-medium">{p.model_name}</p>
                                <p className="text-xs text-muted-foreground">{p.brand} • <span className="font-mono text-indigo-600">{p.product_code}</span></p>
                              </div>
                            </TableCell>
                            <TableCell className="text-right text-sm text-muted-foreground">{p.mrp ? fmtINR(Number(p.mrp)) : '—'}</TableCell>
                            <TableCell className="text-right text-sm font-medium">{Number(p.units_sold)}</TableCell>
                            <TableCell className="text-right text-sm font-medium">{fmtINR(Number(p.total_revenue))}</TableCell>
                            <TableCell className="text-right text-sm text-orange-700">{fmtINR(Number(p.total_cogs))}</TableCell>
                            <TableCell className={`text-right text-sm font-semibold ${grossProfit >= 0 ? 'text-green-700' : 'text-red-700'}`}>{fmtINR(grossProfit)}</TableCell>
                            <TableCell className="text-right">
                              <Badge variant="outline" className={`text-xs font-semibold ${marginPct >= 20 ? 'bg-green-100 text-green-800 border-green-200' : marginPct >= 10 ? 'bg-yellow-100 text-yellow-800 border-yellow-200' : marginPct >= 0 ? 'bg-orange-100 text-orange-800 border-orange-200' : 'bg-red-100 text-red-800 border-red-200'}`}>
                                {marginPct.toFixed(1)}%
                              </Badge>
                            </TableCell>
                            <TableCell className="text-right text-sm text-purple-700">{Number(p.total_discounts) > 0 ? fmtINR(Number(p.total_discounts)) : '—'}</TableCell>
                            <TableCell className="text-center">
                              {mgrApprovals > 0 ? (
                                <Badge variant="outline" className="text-xs bg-purple-100 text-purple-800 border-purple-200">{mgrApprovals}</Badge>
                              ) : (
                                <span className="text-xs text-muted-foreground">—</span>
                              )}
                            </TableCell>
                          </TableRow>
                        )
                      })}
                    </TableBody>
                  </Table>
                </div>
              ) : (
                <div className="text-center py-12 space-y-2">
                  <TrendingUp className="h-8 w-8 mx-auto text-muted-foreground/30" />
                  <p className="text-sm text-muted-foreground">No sales data for this period.</p>
                  <p className="text-xs text-muted-foreground">Process POS sales to see product-level margin analysis here.</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Discount analysis */}
          {marginData && marginData.summary.totalDiscounts > 0 && (
            <Card className="border-purple-200">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-sm font-semibold uppercase tracking-widest text-purple-600">
                  Discount Analysis
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="p-4 bg-purple-50 rounded-xl text-center">
                    <p className="text-xs uppercase tracking-widest text-purple-500 mb-1">Total Discounts Given</p>
                    <p className="text-xl font-bold text-purple-800">{fmtINR(marginData.summary.totalDiscounts)}</p>
                  </div>
                  <div className="p-4 bg-purple-50 rounded-xl text-center">
                    <p className="text-xs uppercase tracking-widest text-purple-500 mb-1">Discount as % of Revenue</p>
                    <p className="text-xl font-bold text-purple-800">
                      {marginData.summary.totalRevenue > 0 ? (marginData.summary.totalDiscounts / marginData.summary.totalRevenue * 100).toFixed(1) : '0.0'}%
                    </p>
                  </div>
                  <div className="p-4 bg-purple-50 rounded-xl text-center">
                    <p className="text-xs uppercase tracking-widest text-purple-500 mb-1">Products With Discounts</p>
                    <p className="text-xl font-bold text-purple-800">
                      {(marginData.products ?? []).filter(p => Number(p.total_discounts) > 0).length}
                      <span className="text-sm font-normal text-purple-500"> of {marginData.products.length}</span>
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

        </div>
      )}
      </div>{/* end finance-printable */}

      {/* ── Off-screen print template (react-to-print target) ── */}
      <div className="fixed -left-[9999px] top-0">
        <FinancePrintTemplate
          ref={printRef}
          reportType={printReportType}
          fromDate={dateFrom}
          toDate={dateTo}
          plRevenue={pl?.revenue ?? []}
          plExpenses={pl?.expenses ?? []}
          totalRevenue={pl?.totalRevenue ?? 0}
          totalExpenses={pl?.totalExpenses ?? 0}
          netProfit={pl?.netProfit ?? 0}
          bsAssets={bs?.assets ?? []}
          bsLiabilities={bs?.liabilities ?? []}
          bsEquity={bs?.equity ?? []}
          gstRows={gst?.gst ?? []}
          journalEntries={journalEntries}
          expenses={expenses}
          marginProducts={marginData?.products ?? []}
          marginSummary={marginData?.summary}
        />
      </div>

      {/* ── Manual Journal Drawer ────────────────── */}
      <ManualJournalDrawer
        open={manualJournalOpen}
        onOpenChange={setManualJournalOpen}
        branchId={branchId}
        isAdmin={isAdmin}
        branches={branchList}
        onSuccess={handleJournalPosted}
      />

    </div>
  )
}

// ── Journal Ledger Drill-Down Row (B10) ─────────────
// Self-contained component: manages its own expand/collapse state and
// fetches the debit/credit lines on-demand when the user clicks.
type JournalLine = {
  id: string
  accountCode: string
  accountName: string
  accountType: string
  debit: number
  credit: number
  description: string
}

function JournalEntryRow({ entry }: { entry: JournalEntry }) {
  const [isOpen, setIsOpen] = useState(false)
  const [lines, setLines] = useState<JournalLine[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  async function handleToggle() {
    if (isOpen) {
      setIsOpen(false)
      return
    }
    // Only fetch if we haven't already
    if (lines.length === 0) {
      setLoading(true)
      setError('')
      try {
        const res = await getJournalLines({ journalEntryId: entry.id })
        if (res.success) {
          setLines(res.lines)
        } else {
          setError(res.error ?? 'Failed to load journal lines')
        }
      } catch {
        setError('Failed to load journal lines')
      } finally {
        setLoading(false)
      }
    }
    setIsOpen(true)
  }

  return (
    <>
      <TableRow
        className="cursor-pointer hover:bg-slate-50/80 transition-colors"
        onClick={handleToggle}
      >
        <TableCell className="w-8 px-2">
          {isOpen
            ? <ChevronDown className="h-4 w-4 text-indigo-500" />
            : <ChevronRight className="h-4 w-4 text-slate-400" />}
        </TableCell>
        <TableCell className="text-xs text-muted-foreground whitespace-nowrap">
          {fmtDate(entry.date)}
        </TableCell>
        <TableCell className="text-sm max-w-xs truncate">
          {entry.description}
        </TableCell>
        <TableCell>
          <Badge variant="outline" className={`text-xs ${sourceColor(entry.referenceSource)}`}>
            {entry.referenceSource}
          </Badge>
        </TableCell>
        <TableCell className="text-xs text-muted-foreground">
          {entry.branchName ?? '—'}
        </TableCell>
        <TableCell className="text-xs text-muted-foreground">
          {entry.financialYear}
        </TableCell>
        <TableCell>
          <Badge variant="outline" className="text-xs">
            {entry.autoGenerated ? 'Auto' : 'Manual'}
          </Badge>
        </TableCell>
        <TableCell className="text-sm font-semibold text-slate-700 text-right tabular-nums">
          {fmtINR(entry.amount)}
        </TableCell>
        <TableCell>
          <Badge variant="outline" className={`text-xs ${statusColor(entry.status)}`}>
            {entry.status}
          </Badge>
        </TableCell>
      </TableRow>

      {/* ── Expanded detail sub-row ── */}
      {isOpen && (
        <TableRow className="bg-slate-50/60">
          <TableCell colSpan={9} className="p-0">
            <div className="px-8 py-4 border-l-4 border-indigo-300">
              {loading ? (
                <div className="flex items-center gap-2 text-sm text-muted-foreground py-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Loading journal lines…
                </div>
              ) : error ? (
                <p className="text-sm text-red-500 py-2">{error}</p>
              ) : lines.length === 0 ? (
                <p className="text-sm text-muted-foreground py-2">No lines recorded for this entry.</p>
              ) : (
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-xs text-muted-foreground border-b">
                      <th className="text-left py-1.5 pr-4 font-medium">Account</th>
                      <th className="text-left py-1.5 pr-4 font-medium">Description</th>
                      <th className="text-right py-1.5 pr-4 font-medium w-28">Debit (₹)</th>
                      <th className="text-right py-1.5 font-medium w-28">Credit (₹)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {lines.map((line) => (
                      <tr key={line.id} className="border-b border-slate-100 last:border-0">
                        <td className="py-1.5 pr-4">
                          <span className="font-mono text-xs text-slate-500 mr-1.5">{line.accountCode}</span>
                          <span className="text-slate-700">{line.accountName}</span>
                        </td>
                        <td className="py-1.5 pr-4 text-muted-foreground max-w-xs truncate">
                          {line.description || '—'}
                        </td>
                        <td className={`py-1.5 pr-4 text-right tabular-nums font-medium ${
                          line.debit > 0 ? 'text-rose-600' : 'text-slate-300'
                        }`}>
                          {line.debit > 0 ? fmtINR(line.debit) : '—'}
                        </td>
                        <td className={`py-1.5 text-right tabular-nums font-medium ${
                          line.credit > 0 ? 'text-emerald-600' : 'text-slate-300'
                        }`}>
                          {line.credit > 0 ? fmtINR(line.credit) : '—'}
                        </td>
                      </tr>
                    ))}
                    {/* Totals footer */}
                    <tr className="border-t-2 border-slate-200 font-semibold">
                      <td colSpan={2} className="py-1.5 pr-4 text-right text-xs text-muted-foreground">Total</td>
                      <td className="py-1.5 pr-4 text-right tabular-nums text-rose-700">
                        {fmtINR(lines.reduce((s, l) => s + l.debit, 0))}
                      </td>
                      <td className="py-1.5 text-right tabular-nums text-emerald-700">
                        {fmtINR(lines.reduce((s, l) => s + l.credit, 0))}
                      </td>
                    </tr>
                  </tbody>
                </table>
              )}
            </div>
          </TableCell>
        </TableRow>
      )}
    </>
  )
}
