"use client"

import { useState, useTransition } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import {
  Card, CardContent, CardHeader, CardTitle
} from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Table, TableBody, TableCell, TableHead,
  TableHeader, TableRow
} from '@/components/ui/table'
import {
  TrendingUp, TrendingDown, Scale, Receipt,
  BookOpen, LayoutDashboard, Plus, CheckCircle2,
  XCircle, Clock, ArrowUpRight, ArrowDownRight,
  Wallet, FileText, IndianRupee
} from 'lucide-react'
import {
  createExpenseRecord, approveExpense, rejectExpense
} from '@/actions/finance'

// ── Types ───────────────────────────────────────────

type PLData = {
  revenue: Array<{ code: string; name: string; net: string }>
  expenses: Array<{ code: string; name: string; net: string }>
  totalRevenue: number
  totalExpenses: number
  netProfit: number
} | null

type BSData = {
  assets: Array<{ code: string; name: string; balance: string }>
  liabilities: Array<{ code: string; name: string; balance: string }>
  equity: Array<{ code: string; name: string; balance: string }>
} | null

type GSTData = {
  gst: Array<{
    code: string; name: string
    collected: string; paid: string
  }>
} | null

type JournalEntry = {
  id: string
  date: Date
  description: string
  referenceSource: string
  referenceId: string | null
  branchId: string
  branchName: string | null
  financialYear: string
  status: string
  autoGenerated: boolean
}

type Expense = {
  id: string
  branch_id: string
  created_by: string
  amount: string
  expense_account: string
  payment_account: string
  description: string
  receipt_url: string | null
  status: string
  approved_by: string | null
  approved_at: Date | null
  journal_entry_id: string | null
  created_at: Date
}

// ── Helper formatters ───────────────────────────────

function fmtINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
  }).format(amount)
}

function fmtDate(date: Date | string): string {
  return new Date(date).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
  })
}

function sourceColor(source: string): string {
  const map: Record<string, string> = {
    GRN:     'bg-blue-100 text-blue-800 border-blue-200',
    SALES:   'bg-green-100 text-green-800 border-green-200',
    EXPENSE: 'bg-orange-100 text-orange-800 border-orange-200',
    MANUAL:  'bg-slate-100 text-slate-600 border-slate-200',
  }
  return map[source] ?? map['MANUAL']
}

function statusColor(status: string): string {
  const map: Record<string, string> = {
    pending:  'bg-yellow-100 text-yellow-800 border-yellow-200',
    approved: 'bg-green-100 text-green-800 border-green-200',
    rejected: 'bg-red-100 text-red-800 border-red-200',
    posted:   'bg-slate-100 text-slate-600 border-slate-200',
  }
  return map[status] ?? map['posted']
}

// ── EXPENSE ACCOUNTS for dropdown ──────────────────
const EXPENSE_ACCOUNTS = [
  { code: '5010', name: 'Cost of Goods Sold' },
  { code: '5020', name: 'Freight & Logistics' },
  { code: '5030', name: 'Utilities' },
  { code: '5040', name: 'Rent' },
  { code: '5050', name: 'Salaries & Wages' },
  { code: '5060', name: 'Marketing & Advertising' },
  { code: '5070', name: 'Miscellaneous Expense' },
]

const PAYMENT_ACCOUNTS = [
  { code: '1010', name: 'Cash & Petty Cash' },
  { code: '1020', name: 'Bank Accounts' },
]

// ── Main component ──────────────────────────────────

export default function AccountingClient({
  activeTab,
  isAdmin,
  pl,
  bs,
  gst,
  journal,
  expenses: initialExpenses,
  userId,
  branchId,
}: {
  activeTab: string
  isAdmin: boolean
  pl: PLData
  bs: BSData
  gst: GSTData
  journal: JournalEntry[]
  expenses: Expense[]
  userId: string
  branchId: string | null
}) {
  const router = useRouter()
  const [tab, setTab] = useState(activeTab)
  const [expenses, setExpenses] = useState(initialExpenses)

  // Expense form state
  const [showExpenseForm, setShowExpenseForm] = useState(false)
  const [expAmount, setExpAmount] = useState('')
  const [expAccount, setExpAccount] = useState('5070')
  const [expPayment, setExpPayment] = useState('1010')
  const [expDesc, setExpDesc] = useState('')
  const [expError, setExpError] = useState('')
  const [isPending, startTransition] = useTransition()

  function switchTab(t: string) {
    setTab(t)
    router.push(`/accounting?tab=${t}`, { scroll: false })
  }

  // ── Submit expense ────────────────────────────────
  async function handleSubmitExpense() {
    setExpError('')
    if (!expAmount || Number(expAmount) <= 0) {
      setExpError('Enter a valid amount')
      return
    }
    if (!expDesc.trim()) {
      setExpError('Description is required')
      return
    }
    startTransition(async () => {
      const result = await createExpenseRecord({
        amount: Number(expAmount),
        expenseAccount: expAccount,
        paymentAccount: expPayment,
        description: expDesc.trim(),
      })
      if (result.success) {
        setExpenses(prev => [result.record as any, ...prev])
        setShowExpenseForm(false)
        setExpAmount('')
        setExpDesc('')
      } else {
        setExpError(result.error ?? 'Failed to submit')
      }
    })
  }

  // ── Approve / Reject expense ──────────────────────
  async function handleApprove(id: string) {
    startTransition(async () => {
      const result = await approveExpense({ expenseId: id })
      if (result.success) {
        setExpenses(prev => prev.map(e =>
          e.id === id ? { ...e, status: 'approved' } : e
        ))
      }
    })
  }

  async function handleReject(id: string) {
    startTransition(async () => {
      const result = await rejectExpense({ expenseId: id })
      if (result.success) {
        setExpenses(prev => prev.map(e =>
          e.id === id ? { ...e, status: 'rejected' } : e
        ))
      }
    })
  }

  // ── Tab definitions ───────────────────────────────
  const tabs = [
    { id: 'dashboard', label: 'Dashboard',
      icon: LayoutDashboard },
    { id: 'balance-sheet', label: 'Balance Sheet',
      icon: Scale },
    { id: 'journal',   label: 'Journal Ledger',
      icon: BookOpen },
    { id: 'expenses',  label: 'Expenses',
      icon: Receipt },
  ]

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">

      {/* ── Page header ── */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight
            flex items-center gap-2">
            <Wallet className="h-6 w-6 text-indigo-600" />
            Finance & Accounts
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Automated double-entry accounting •
            {isAdmin ? ' All Branches' : ' Your Branch'}
          </p>
        </div>
      </div>

      {/* ── Tab bar ── */}
      <div className="flex gap-1 border-b">
        {tabs.map(t => (
          <button
            key={t.id}
            onClick={() => switchTab(t.id)}
            className={`flex items-center gap-2 px-4 py-2.5
              text-sm font-medium border-b-2 transition-colors
              ${tab === t.id
                ? 'border-indigo-600 text-indigo-600'
                : 'border-transparent text-muted-foreground hover:text-foreground'
              }`}
          >
            <t.icon className="h-4 w-4" />
            {t.label}
          </button>
        ))}
      </div>

      {/* ══════════════════════════════════════════
          TAB: DASHBOARD
      ══════════════════════════════════════════ */}
      {tab === 'dashboard' && (
        <div className="space-y-6">

          {/* P&L summary cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card className="border-green-200 bg-green-50/30">
              <CardContent className="pt-6">
                <div className="flex items-center
                  justify-between">
                  <div>
                    <p className="text-xs font-semibold
                      uppercase tracking-widest
                      text-green-700">
                      Total Revenue
                    </p>
                    <p className="text-2xl font-bold
                      text-green-800 mt-1">
                      {fmtINR(pl?.totalRevenue ?? 0)}
                    </p>
                    <p className="text-xs text-green-600 mt-1">
                      Current financial year
                    </p>
                  </div>
                  <div className="p-3 bg-green-100
                    rounded-full">
                    <TrendingUp className="h-5 w-5
                      text-green-600" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-red-200 bg-red-50/30">
              <CardContent className="pt-6">
                <div className="flex items-center
                  justify-between">
                  <div>
                    <p className="text-xs font-semibold
                      uppercase tracking-widest text-red-700">
                      Total Expenses
                    </p>
                    <p className="text-2xl font-bold
                      text-red-800 mt-1">
                      {fmtINR(pl?.totalExpenses ?? 0)}
                    </p>
                    <p className="text-xs text-red-600 mt-1">
                      Current financial year
                    </p>
                  </div>
                  <div className="p-3 bg-red-100 rounded-full">
                    <TrendingDown className="h-5 w-5
                      text-red-600" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className={`border-2 ${
              (pl?.netProfit ?? 0) >= 0
                ? 'border-indigo-200 bg-indigo-50/30'
                : 'border-orange-200 bg-orange-50/30'
            }`}>
              <CardContent className="pt-6">
                <div className="flex items-center
                  justify-between">
                  <div>
                    <p className="text-xs font-semibold
                      uppercase tracking-widest
                      text-indigo-700">
                      Net Profit / Loss
                    </p>
                    <p className={`text-2xl font-bold mt-1
                      ${(pl?.netProfit ?? 0) >= 0
                        ? 'text-indigo-800'
                        : 'text-orange-700'
                      }`}>
                      {fmtINR(pl?.netProfit ?? 0)}
                    </p>
                    <p className="text-xs text-muted-foreground mt-1">
                      {(pl?.netProfit ?? 0) >= 0
                        ? '▲ Profitable'
                        : '▼ Net loss'}
                    </p>
                  </div>
                  <div className={`p-3 rounded-full ${
                    (pl?.netProfit ?? 0) >= 0
                      ? 'bg-indigo-100'
                      : 'bg-orange-100'
                  }`}>
                    <Scale className={`h-5 w-5 ${
                      (pl?.netProfit ?? 0) >= 0
                        ? 'text-indigo-600'
                        : 'text-orange-600'
                    }`} />
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* GST Summary */}
          {gst && gst.gst.length > 0 && (
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-slate-500">
                  GST Position — Current FY
                </CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Account</TableHead>
                      <TableHead className="text-right">
                        Collected (Output)
                      </TableHead>
                      <TableHead className="text-right">
                        Paid / ITC (Input)
                      </TableHead>
                      <TableHead className="text-right">
                        Net Payable
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {gst.gst.map(row => (
                      <TableRow key={row.code}>
                        <TableCell className="font-medium">
                          <span className="text-xs text-muted-foreground mr-2">
                            {row.code}
                          </span>
                          {row.name}
                        </TableCell>
                        <TableCell className="text-right text-green-700">
                          {fmtINR(Number(row.collected))}
                        </TableCell>
                        <TableCell className="text-right text-blue-700">
                          {fmtINR(Number(row.paid))}
                        </TableCell>
                        <TableCell className={`text-right font-semibold ${
                          Number(row.collected) - Number(row.paid) > 0
                            ? 'text-red-700'
                            : 'text-green-700'
                        }`}>
                          {fmtINR(
                            Number(row.collected) - Number(row.paid)
                          )}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}

          {/* P&L breakdown */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

            {/* Revenue breakdown */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-green-600">
                  Revenue Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent>
                {pl?.revenue.length ? (
                  <div className="space-y-2">
                    {pl.revenue.map(r => (
                      <div key={r.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {r.code}
                          </span>
                          {r.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-green-700">
                          {fmtINR(Number(r.net))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-green-200">
                      <span className="text-sm font-bold">
                        Total Revenue
                      </span>
                      <span className="text-sm font-bold
                        text-green-700">
                        {fmtINR(pl.totalRevenue)}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">
                    No revenue recorded yet
                  </p>
                )}
              </CardContent>
            </Card>

            {/* Expense breakdown */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-red-600">
                  Expense Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent>
                {pl?.expenses.length ? (
                  <div className="space-y-2">
                    {pl.expenses.map(e => (
                      <div key={e.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {e.code}
                          </span>
                          {e.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-red-700">
                          {fmtINR(Number(e.net))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-red-200">
                      <span className="text-sm font-bold">
                        Total Expenses
                      </span>
                      <span className="text-sm font-bold
                        text-red-700">
                        {fmtINR(pl.totalExpenses)}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">
                    No expenses recorded yet
                  </p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Recent journal entries */}
          <Card>
            <CardHeader className="pb-3 flex flex-row
              items-center justify-between">
              <CardTitle className="text-sm font-semibold
                uppercase tracking-widest text-slate-500">
                Recent Journal Entries
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => switchTab('journal')}
                className="text-xs text-indigo-600
                  hover:text-indigo-700"
              >
                View All →
              </Button>
            </CardHeader>
            <CardContent>
              {journal.length > 0 ? (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead>Source</TableHead>
                      <TableHead>Branch</TableHead>
                      <TableHead>FY</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {journal.slice(0, 10).map(entry => (
                      <TableRow key={entry.id}>
                        <TableCell className="text-xs
                          text-muted-foreground whitespace-nowrap">
                          {fmtDate(entry.date)}
                        </TableCell>
                        <TableCell className="text-sm
                          max-w-xs truncate">
                          {entry.description}
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline"
                            className={`text-xs ${
                              sourceColor(entry.referenceSource)
                            }`}>
                            {entry.referenceSource}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-xs
                          text-muted-foreground">
                          {entry.branchName ?? '—'}
                        </TableCell>
                        <TableCell className="text-xs
                          text-muted-foreground">
                          {entry.financialYear}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              ) : (
                <p className="text-sm text-muted-foreground
                  text-center py-8">
                  No journal entries yet. They will appear
                  automatically after GRN receipts and
                  POS sales.
                </p>
              )}
            </CardContent>
          </Card>
        </div>
      )}

      {/* ══════════════════════════════════════════
          TAB: BALANCE SHEET
      ══════════════════════════════════════════ */}
      {tab === 'balance-sheet' && (
        <div className="space-y-4">

          {/* Accounting equation banner */}
          <Card className="bg-slate-900 text-white border-0">
            <CardContent className="pt-6">
              <div className="flex items-center
                justify-between text-center">
                <div>
                  <p className="text-xs uppercase tracking-widest
                    text-slate-400 mb-1">Total Assets</p>
                  <p className="text-2xl font-bold text-white">
                    {fmtINR(
                      (bs?.assets ?? []).reduce(
                        (s, a) => s + Number(a.balance), 0
                      )
                    )}
                  </p>
                </div>
                <div className="text-2xl font-light
                  text-slate-400">=</div>
                <div>
                  <p className="text-xs uppercase tracking-widest
                    text-slate-400 mb-1">Total Liabilities</p>
                  <p className="text-2xl font-bold
                    text-red-400">
                    {fmtINR(
                      (bs?.liabilities ?? []).reduce(
                        (s, l) => s + Number(l.balance), 0
                      )
                    )}
                  </p>
                </div>
                <div className="text-2xl font-light
                  text-slate-400">+</div>
                <div>
                  <p className="text-xs uppercase tracking-widest
                    text-slate-400 mb-1">Total Equity</p>
                  <p className="text-2xl font-bold
                    text-green-400">
                    {fmtINR(
                      (bs?.equity ?? []).reduce(
                        (s, e) => s + Number(e.balance), 0
                      )
                    )}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Three columns: Assets | Liabilities | Equity */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

            {/* Assets */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-blue-600">
                  Assets
                </CardTitle>
              </CardHeader>
              <CardContent>
                {(bs?.assets ?? []).length > 0 ? (
                  <div className="space-y-2">
                    {(bs?.assets ?? []).map(a => (
                      <div key={a.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {a.code}
                          </span>
                          {a.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-blue-700">
                          {fmtINR(Number(a.balance))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-blue-200">
                      <span className="text-sm font-bold">
                        Total
                      </span>
                      <span className="text-sm font-bold
                        text-blue-700">
                        {fmtINR(
                          (bs?.assets ?? []).reduce(
                            (s, a) => s + Number(a.balance), 0
                          )
                        )}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">No asset entries</p>
                )}
              </CardContent>
            </Card>

            {/* Liabilities */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-red-600">
                  Liabilities
                </CardTitle>
              </CardHeader>
              <CardContent>
                {(bs?.liabilities ?? []).length > 0 ? (
                  <div className="space-y-2">
                    {(bs?.liabilities ?? []).map(l => (
                      <div key={l.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {l.code}
                          </span>
                          {l.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-red-700">
                          {fmtINR(Number(l.balance))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-red-200">
                      <span className="text-sm font-bold">
                        Total
                      </span>
                      <span className="text-sm font-bold
                        text-red-700">
                        {fmtINR(
                          (bs?.liabilities ?? []).reduce(
                            (s, l) => s + Number(l.balance), 0
                          )
                        )}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">No liability entries</p>
                )}
              </CardContent>
            </Card>

            {/* Equity */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold
                  uppercase tracking-widest text-green-600">
                  Equity
                </CardTitle>
              </CardHeader>
              <CardContent>
                {(bs?.equity ?? []).length > 0 ? (
                  <div className="space-y-2">
                    {(bs?.equity ?? []).map(e => (
                      <div key={e.code}
                        className="flex justify-between
                          items-center py-1.5 border-b
                          border-slate-100 last:border-0">
                        <span className="text-sm">
                          <span className="text-xs
                            text-muted-foreground mr-2">
                            {e.code}
                          </span>
                          {e.name}
                        </span>
                        <span className="text-sm font-semibold
                          text-green-700">
                          {fmtINR(Number(e.balance))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between
                      items-center pt-2 border-t-2
                      border-green-200">
                      <span className="text-sm font-bold">
                        Total
                      </span>
                      <span className="text-sm font-bold
                        text-green-700">
                        {fmtINR(
                          (bs?.equity ?? []).reduce(
                            (s, e) => s + Number(e.balance), 0
                          )
                        )}
                      </span>
                    </div>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground
                    text-center py-4">No equity entries</p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Balance check */}
          {bs && (() => {
            const totalAssets = bs.assets.reduce(
              (s, a) => s + Number(a.balance), 0)
            const totalLiabEquity =
              bs.liabilities.reduce(
                (s, l) => s + Number(l.balance), 0) +
              bs.equity.reduce(
                (s, e) => s + Number(e.balance), 0)
            const diff = Math.abs(totalAssets - totalLiabEquity)
            return diff > 1 ? (
              <Card className="border-orange-200 bg-orange-50">
                <CardContent className="pt-4 pb-4">
                  <p className="text-sm text-orange-700
                    text-center">
                    ⚠️ Balance sheet is out of balance by
                    {' '}{fmtINR(diff)}. This may indicate
                    missing opening balance entries.
                  </p>
                </CardContent>
              </Card>
            ) : (
              <Card className="border-green-200 bg-green-50">
                <CardContent className="pt-4 pb-4">
                  <p className="text-sm text-green-700
                    text-center flex items-center
                    justify-center gap-2">
                    <CheckCircle2 className="h-4 w-4" />
                    Balance sheet is balanced ✓
                  </p>
                </CardContent>
              </Card>
            )
          })()}
        </div>
      )}

      {/* ══════════════════════════════════════════
          TAB: JOURNAL LEDGER
      ══════════════════════════════════════════ */}
      {tab === 'journal' && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2">
              <BookOpen className="h-4 w-4 text-indigo-600" />
              Journal Ledger
            </CardTitle>
          </CardHeader>
          <CardContent>
            {journal.length > 0 ? (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Description</TableHead>
                    <TableHead>Source</TableHead>
                    <TableHead>Branch</TableHead>
                    <TableHead>FY</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {journal.map(entry => (
                    <TableRow key={entry.id}>
                      <TableCell className="text-xs
                        text-muted-foreground whitespace-nowrap">
                        {fmtDate(entry.date)}
                      </TableCell>
                      <TableCell className="text-sm
                        max-w-xs truncate">
                        {entry.description}
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline"
                          className={`text-xs ${
                            sourceColor(entry.referenceSource)
                          }`}>
                          {entry.referenceSource}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-xs
                        text-muted-foreground">
                        {entry.branchName ?? '—'}
                      </TableCell>
                      <TableCell className="text-xs
                        text-muted-foreground">
                        {entry.financialYear}
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline"
                          className="text-xs">
                          {entry.autoGenerated
                            ? 'Auto' : 'Manual'}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline"
                          className={`text-xs ${
                            statusColor(entry.status)
                          }`}>
                          {entry.status}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            ) : (
              <p className="text-sm text-muted-foreground
                text-center py-12">
                No journal entries yet. GRN receipts and
                POS sales automatically create entries here.
              </p>
            )}
          </CardContent>
        </Card>
      )}

      {/* ══════════════════════════════════════════
          TAB: EXPENSES
      ══════════════════════════════════════════ */}
      {tab === 'expenses' && (
        <div className="space-y-4">

          {/* Submit expense button + form */}
          <div className="flex justify-end">
            <Button
              onClick={() => setShowExpenseForm(!showExpenseForm)}
              className="gap-2 bg-[#001529] hover:bg-[#002a52]
                text-white"
            >
              <Plus className="h-4 w-4" />
              Submit Expense
            </Button>
          </div>

          {showExpenseForm && (
            <Card className="border-indigo-200">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm">
                  New Expense Record
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-semibold
                      uppercase tracking-widest text-slate-500">
                      Amount (₹)
                    </Label>
                    <Input
                      type="number"
                      placeholder="0.00"
                      value={expAmount}
                      onChange={e => setExpAmount(e.target.value)}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-semibold
                      uppercase tracking-widest text-slate-500">
                      Expense Category
                    </Label>
                    <select
                      value={expAccount}
                      onChange={e => setExpAccount(e.target.value)}
                      className="w-full text-sm border rounded-md
                        px-3 py-2 bg-white focus:outline-none
                        focus:ring-1 focus:ring-indigo-500"
                    >
                      {EXPENSE_ACCOUNTS.map(a => (
                        <option key={a.code} value={a.code}>
                          {a.name}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-semibold
                    uppercase tracking-widest text-slate-500">
                    Payment Source
                  </Label>
                  <select
                    value={expPayment}
                    onChange={e => setExpPayment(e.target.value)}
                    className="w-full text-sm border rounded-md
                      px-3 py-2 bg-white focus:outline-none
                      focus:ring-1 focus:ring-indigo-500"
                  >
                    {PAYMENT_ACCOUNTS.map(a => (
                      <option key={a.code} value={a.code}>
                        {a.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-semibold
                    uppercase tracking-widest text-slate-500">
                    Description
                  </Label>
                  <Textarea
                    placeholder="Brief description of the expense..."
                    value={expDesc}
                    onChange={e => setExpDesc(e.target.value)}
                    className="min-h-[80px]"
                  />
                </div>

                {expError && (
                  <p className="text-sm text-red-600">
                    {expError}
                  </p>
                )}

                <div className="flex gap-2 justify-end">
                  <Button
                    variant="outline"
                    onClick={() => setShowExpenseForm(false)}
                  >
                    Cancel
                  </Button>
                  <Button
                    onClick={handleSubmitExpense}
                    disabled={isPending}
                    className="bg-[#001529] hover:bg-[#002a52]
                      text-white"
                  >
                    {isPending ? 'Submitting...' : 'Submit'}
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Expense list */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2">
                <Receipt className="h-4 w-4 text-orange-500" />
                Expense Records
              </CardTitle>
            </CardHeader>
            <CardContent>
              {expenses.length > 0 ? (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead>Category</TableHead>
                      <TableHead>Payment</TableHead>
                      <TableHead className="text-right">
                        Amount
                      </TableHead>
                      <TableHead>Status</TableHead>
                      {isAdmin && (
                        <TableHead>Actions</TableHead>
                      )}
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {expenses.map(exp => (
                      <TableRow key={exp.id}>
                        <TableCell className="text-xs
                          text-muted-foreground whitespace-nowrap">
                          {fmtDate(exp.created_at)}
                        </TableCell>
                        <TableCell className="text-sm
                          max-w-xs truncate">
                          {exp.description}
                        </TableCell>
                        <TableCell className="text-xs">
                          {EXPENSE_ACCOUNTS.find(
                            a => a.code === exp.expense_account
                          )?.name ?? exp.expense_account}
                        </TableCell>
                        <TableCell className="text-xs">
                          {PAYMENT_ACCOUNTS.find(
                            a => a.code === exp.payment_account
                          )?.name ?? exp.payment_account}
                        </TableCell>
                        <TableCell className="text-right
                          font-semibold">
                          {fmtINR(Number(exp.amount))}
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline"
                            className={`text-xs ${
                              statusColor(exp.status)
                            }`}>
                            {exp.status === 'pending' && (
                              <Clock className="h-3 w-3 mr-1" />
                            )}
                            {exp.status === 'approved' && (
                              <CheckCircle2 className="h-3 w-3 mr-1" />
                            )}
                            {exp.status === 'rejected' && (
                              <XCircle className="h-3 w-3 mr-1" />
                            )}
                            {exp.status.charAt(0).toUpperCase()
                             + exp.status.slice(1)}
                          </Badge>
                        </TableCell>
                        {isAdmin && (
                          <TableCell>
                            {exp.status === 'pending' && (
                              <div className="flex gap-1">
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-7 text-xs
                                    text-green-700
                                    border-green-200
                                    hover:bg-green-50"
                                  onClick={() =>
                                    handleApprove(exp.id)}
                                  disabled={isPending}
                                >
                                  Approve
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-7 text-xs
                                    text-red-700
                                    border-red-200
                                    hover:bg-red-50"
                                  onClick={() =>
                                    handleReject(exp.id)}
                                  disabled={isPending}
                                >
                                  Reject
                                </Button>
                              </div>
                            )}
                          </TableCell>
                        )}
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              ) : (
                <p className="text-sm text-muted-foreground
                  text-center py-12">
                  No expenses recorded. Click Submit Expense
                  to add one.
                </p>
              )}
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  )
}
